// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	upgradeDevGroupRelationFieldNames          = builder.RawFieldNames(&UpgradeDevGroupRelation{})
	upgradeDevGroupRelationRows                = strings.Join(upgradeDevGroupRelationFieldNames, ",")
	upgradeDevGroupRelationRowsExpectAutoSet   = strings.Join(stringx.Remove(upgradeDevGroupRelationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	upgradeDevGroupRelationRowsWithPlaceHolder = strings.Join(stringx.Remove(upgradeDevGroupRelationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	upgradeDevGroupRelationModel interface {
		Insert(ctx context.Context, data *UpgradeDevGroupRelation) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UpgradeDevGroupRelation, error)
		Update(ctx context.Context, data *UpgradeDevGroupRelation) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUpgradeDevGroupRelationModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UpgradeDevGroupRelation struct {
		Id         int64     `db:"id"`           // ID
		DevId      uint64    `db:"dev_id"`       // 设备id
		DevGroupId uint64    `db:"dev_group_id"` // 设备分组 id
		IsDel      int64     `db:"is_del"`       // 是否删除 0：正常；1：已删除
		CreateAt   time.Time `db:"create_at"`    // 创建时间
		UpdateAt   time.Time `db:"update_at"`    // 修改时间
	}
)

func newUpgradeDevGroupRelationModel(conn sqlx.SqlConn) *defaultUpgradeDevGroupRelationModel {
	return &defaultUpgradeDevGroupRelationModel{
		conn:  conn,
		table: "`upgrade_dev_group_relation`",
	}
}

func (m *defaultUpgradeDevGroupRelationModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUpgradeDevGroupRelationModel) FindOne(ctx context.Context, id int64) (*UpgradeDevGroupRelation, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", upgradeDevGroupRelationRows, m.table)
	var resp UpgradeDevGroupRelation
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUpgradeDevGroupRelationModel) Insert(ctx context.Context, data *UpgradeDevGroupRelation) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, upgradeDevGroupRelationRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DevId, data.DevGroupId, data.IsDel)
	return ret, err
}

func (m *defaultUpgradeDevGroupRelationModel) Update(ctx context.Context, data *UpgradeDevGroupRelation) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, upgradeDevGroupRelationRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.DevId, data.DevGroupId, data.IsDel, data.Id)
	return err
}

func (m *defaultUpgradeDevGroupRelationModel) tableName() string {
	return m.table
}
