// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	upgradeDevsFieldNames          = builder.RawFieldNames(&UpgradeDevs{})
	upgradeDevsRows                = strings.Join(upgradeDevsFieldNames, ",")
	upgradeDevsRowsExpectAutoSet   = strings.Join(stringx.Remove(upgradeDevsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	upgradeDevsRowsWithPlaceHolder = strings.Join(stringx.Remove(upgradeDevsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	upgradeDevsModel interface {
		Insert(ctx context.Context, data *UpgradeDevs) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UpgradeDevs, error)
		Update(ctx context.Context, data *UpgradeDevs) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUpgradeDevsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UpgradeDevs struct {
		Id        int64     `db:"id"`         // ID
		CompanyId int64     `db:"company_id"` // 公司ID
		Key       string    `db:"key"`        // 设备唯一标识
		IsDel     int64     `db:"is_del"`     // 是否删除 0：正常；1：已删除
		CreateAt  time.Time `db:"create_at"`  // 创建时间
		UpdateAt  time.Time `db:"update_at"`  // 修改时间
	}
)

func newUpgradeDevsModel(conn sqlx.SqlConn) *defaultUpgradeDevsModel {
	return &defaultUpgradeDevsModel{
		conn:  conn,
		table: "`upgrade_devs`",
	}
}

func (m *defaultUpgradeDevsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUpgradeDevsModel) FindOne(ctx context.Context, id int64) (*UpgradeDevs, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", upgradeDevsRows, m.table)
	var resp UpgradeDevs
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUpgradeDevsModel) Insert(ctx context.Context, data *UpgradeDevs) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, upgradeDevsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CompanyId, data.Key, data.IsDel)
	return ret, err
}

func (m *defaultUpgradeDevsModel) Update(ctx context.Context, data *UpgradeDevs) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, upgradeDevsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.CompanyId, data.Key, data.IsDel, data.Id)
	return err
}

func (m *defaultUpgradeDevsModel) tableName() string {
	return m.table
}
