// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"upgradelink-admin-upgrade/server/ent/upgradeelectronupgradestrategy"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UpgradeElectronUpgradeStrategy is the model entity for the UpgradeElectronUpgradeStrategy schema.
type UpgradeElectronUpgradeStrategy struct {
	config `json:"-"`
	// ID of the ent.
	// ID
	ID int `json:"id,omitempty"`
	// 公司ID
	CompanyID int `json:"company_id,omitempty"`
	// 是否生效；可通过此控制策略是否生效0：失效；1：生效
	Enable int32 `json:"enable,omitempty"`
	// 任务名称
	Name string `json:"name,omitempty"`
	// 任务描述信息
	Description string `json:"description,omitempty"`
	// electron应用ID
	ElectronID int `json:"electron_id,omitempty"`
	// electron_version_id; 外键electron_version.id
	ElectronVersionID int `json:"electron_version_id,omitempty"`
	// 升级任务开始时间
	BeginDatetime time.Time `json:"begin_datetime,omitempty"`
	// 升级任务结束时间
	EndDatetime time.Time `json:"end_datetime,omitempty"`
	// 升级方式：0：未知方式；1：提示升级；2：静默升级；3: 强制升级
	UpgradeType int32 `json:"upgrade_type,omitempty"`
	// 提示升级描述内容
	PromptUpgradeContent string `json:"prompt_upgrade_content,omitempty"`
	// 指定升级的设备范围：0：全部设备；1：指定设备分组；2：指定机型
	UpgradeDevType int32 `json:"upgrade_dev_type,omitempty"`
	// 升级设备数据：0.当为全部设备时，此字段为空；；1.当指定设备分组时，此字段存储设备分组id；2.当指定设备机型时，此字段存储选中的设备机型id;
	UpgradeDevData string `json:"upgrade_dev_data,omitempty"`
	// 指定升级的应用版本：0：全部版本；1：指定版本
	UpgradeVersionType int32 `json:"upgrade_version_type,omitempty"`
	// 升级设备数据：0.当为全部版本时，此字段为空；；1.当指定应用版本时，此字段存储应用版本id;
	UpgradeVersionData string `json:"upgrade_version_data,omitempty"`
	// 是否开启灰度 0：不开启；1：开启
	IsGray int32 `json:"is_gray,omitempty"`
	// 灰度策略id数据
	GrayData string `json:"gray_data,omitempty"`
	// 是否开启频控 0：不开启；1：开启
	IsFlowLimit int32 `json:"is_flow_limit,omitempty"`
	// 频控策略id数据
	FlowLimitData string `json:"flow_limit_data,omitempty"`
	// 是否删除 0：正常；1：已删除
	IsDel int32 `json:"is_del,omitempty"`
	// 创建时间
	CreateAt time.Time `json:"create_at,omitempty"`
	// 修改时间
	UpdateAt     time.Time `json:"update_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpgradeElectronUpgradeStrategy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upgradeelectronupgradestrategy.FieldID, upgradeelectronupgradestrategy.FieldCompanyID, upgradeelectronupgradestrategy.FieldEnable, upgradeelectronupgradestrategy.FieldElectronID, upgradeelectronupgradestrategy.FieldElectronVersionID, upgradeelectronupgradestrategy.FieldUpgradeType, upgradeelectronupgradestrategy.FieldUpgradeDevType, upgradeelectronupgradestrategy.FieldUpgradeVersionType, upgradeelectronupgradestrategy.FieldIsGray, upgradeelectronupgradestrategy.FieldIsFlowLimit, upgradeelectronupgradestrategy.FieldIsDel:
			values[i] = new(sql.NullInt64)
		case upgradeelectronupgradestrategy.FieldName, upgradeelectronupgradestrategy.FieldDescription, upgradeelectronupgradestrategy.FieldPromptUpgradeContent, upgradeelectronupgradestrategy.FieldUpgradeDevData, upgradeelectronupgradestrategy.FieldUpgradeVersionData, upgradeelectronupgradestrategy.FieldGrayData, upgradeelectronupgradestrategy.FieldFlowLimitData:
			values[i] = new(sql.NullString)
		case upgradeelectronupgradestrategy.FieldBeginDatetime, upgradeelectronupgradestrategy.FieldEndDatetime, upgradeelectronupgradestrategy.FieldCreateAt, upgradeelectronupgradestrategy.FieldUpdateAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpgradeElectronUpgradeStrategy fields.
func (ueus *UpgradeElectronUpgradeStrategy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upgradeelectronupgradestrategy.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ueus.ID = int(value.Int64)
		case upgradeelectronupgradestrategy.FieldCompanyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field company_id", values[i])
			} else if value.Valid {
				ueus.CompanyID = int(value.Int64)
			}
		case upgradeelectronupgradestrategy.FieldEnable:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field enable", values[i])
			} else if value.Valid {
				ueus.Enable = int32(value.Int64)
			}
		case upgradeelectronupgradestrategy.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				ueus.Name = value.String
			}
		case upgradeelectronupgradestrategy.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				ueus.Description = value.String
			}
		case upgradeelectronupgradestrategy.FieldElectronID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field electron_id", values[i])
			} else if value.Valid {
				ueus.ElectronID = int(value.Int64)
			}
		case upgradeelectronupgradestrategy.FieldElectronVersionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field electron_version_id", values[i])
			} else if value.Valid {
				ueus.ElectronVersionID = int(value.Int64)
			}
		case upgradeelectronupgradestrategy.FieldBeginDatetime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field begin_datetime", values[i])
			} else if value.Valid {
				ueus.BeginDatetime = value.Time
			}
		case upgradeelectronupgradestrategy.FieldEndDatetime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_datetime", values[i])
			} else if value.Valid {
				ueus.EndDatetime = value.Time
			}
		case upgradeelectronupgradestrategy.FieldUpgradeType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upgrade_type", values[i])
			} else if value.Valid {
				ueus.UpgradeType = int32(value.Int64)
			}
		case upgradeelectronupgradestrategy.FieldPromptUpgradeContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_upgrade_content", values[i])
			} else if value.Valid {
				ueus.PromptUpgradeContent = value.String
			}
		case upgradeelectronupgradestrategy.FieldUpgradeDevType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upgrade_dev_type", values[i])
			} else if value.Valid {
				ueus.UpgradeDevType = int32(value.Int64)
			}
		case upgradeelectronupgradestrategy.FieldUpgradeDevData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upgrade_dev_data", values[i])
			} else if value.Valid {
				ueus.UpgradeDevData = value.String
			}
		case upgradeelectronupgradestrategy.FieldUpgradeVersionType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upgrade_version_type", values[i])
			} else if value.Valid {
				ueus.UpgradeVersionType = int32(value.Int64)
			}
		case upgradeelectronupgradestrategy.FieldUpgradeVersionData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upgrade_version_data", values[i])
			} else if value.Valid {
				ueus.UpgradeVersionData = value.String
			}
		case upgradeelectronupgradestrategy.FieldIsGray:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field is_gray", values[i])
			} else if value.Valid {
				ueus.IsGray = int32(value.Int64)
			}
		case upgradeelectronupgradestrategy.FieldGrayData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gray_data", values[i])
			} else if value.Valid {
				ueus.GrayData = value.String
			}
		case upgradeelectronupgradestrategy.FieldIsFlowLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field is_flow_limit", values[i])
			} else if value.Valid {
				ueus.IsFlowLimit = int32(value.Int64)
			}
		case upgradeelectronupgradestrategy.FieldFlowLimitData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field flow_limit_data", values[i])
			} else if value.Valid {
				ueus.FlowLimitData = value.String
			}
		case upgradeelectronupgradestrategy.FieldIsDel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field is_del", values[i])
			} else if value.Valid {
				ueus.IsDel = int32(value.Int64)
			}
		case upgradeelectronupgradestrategy.FieldCreateAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_at", values[i])
			} else if value.Valid {
				ueus.CreateAt = value.Time
			}
		case upgradeelectronupgradestrategy.FieldUpdateAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_at", values[i])
			} else if value.Valid {
				ueus.UpdateAt = value.Time
			}
		default:
			ueus.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpgradeElectronUpgradeStrategy.
// This includes values selected through modifiers, order, etc.
func (ueus *UpgradeElectronUpgradeStrategy) Value(name string) (ent.Value, error) {
	return ueus.selectValues.Get(name)
}

// Update returns a builder for updating this UpgradeElectronUpgradeStrategy.
// Note that you need to call UpgradeElectronUpgradeStrategy.Unwrap() before calling this method if this UpgradeElectronUpgradeStrategy
// was returned from a transaction, and the transaction was committed or rolled back.
func (ueus *UpgradeElectronUpgradeStrategy) Update() *UpgradeElectronUpgradeStrategyUpdateOne {
	return NewUpgradeElectronUpgradeStrategyClient(ueus.config).UpdateOne(ueus)
}

// Unwrap unwraps the UpgradeElectronUpgradeStrategy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ueus *UpgradeElectronUpgradeStrategy) Unwrap() *UpgradeElectronUpgradeStrategy {
	_tx, ok := ueus.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpgradeElectronUpgradeStrategy is not a transactional entity")
	}
	ueus.config.driver = _tx.drv
	return ueus
}

// String implements the fmt.Stringer.
func (ueus *UpgradeElectronUpgradeStrategy) String() string {
	var builder strings.Builder
	builder.WriteString("UpgradeElectronUpgradeStrategy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ueus.ID))
	builder.WriteString("company_id=")
	builder.WriteString(fmt.Sprintf("%v", ueus.CompanyID))
	builder.WriteString(", ")
	builder.WriteString("enable=")
	builder.WriteString(fmt.Sprintf("%v", ueus.Enable))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(ueus.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(ueus.Description)
	builder.WriteString(", ")
	builder.WriteString("electron_id=")
	builder.WriteString(fmt.Sprintf("%v", ueus.ElectronID))
	builder.WriteString(", ")
	builder.WriteString("electron_version_id=")
	builder.WriteString(fmt.Sprintf("%v", ueus.ElectronVersionID))
	builder.WriteString(", ")
	builder.WriteString("begin_datetime=")
	builder.WriteString(ueus.BeginDatetime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("end_datetime=")
	builder.WriteString(ueus.EndDatetime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("upgrade_type=")
	builder.WriteString(fmt.Sprintf("%v", ueus.UpgradeType))
	builder.WriteString(", ")
	builder.WriteString("prompt_upgrade_content=")
	builder.WriteString(ueus.PromptUpgradeContent)
	builder.WriteString(", ")
	builder.WriteString("upgrade_dev_type=")
	builder.WriteString(fmt.Sprintf("%v", ueus.UpgradeDevType))
	builder.WriteString(", ")
	builder.WriteString("upgrade_dev_data=")
	builder.WriteString(ueus.UpgradeDevData)
	builder.WriteString(", ")
	builder.WriteString("upgrade_version_type=")
	builder.WriteString(fmt.Sprintf("%v", ueus.UpgradeVersionType))
	builder.WriteString(", ")
	builder.WriteString("upgrade_version_data=")
	builder.WriteString(ueus.UpgradeVersionData)
	builder.WriteString(", ")
	builder.WriteString("is_gray=")
	builder.WriteString(fmt.Sprintf("%v", ueus.IsGray))
	builder.WriteString(", ")
	builder.WriteString("gray_data=")
	builder.WriteString(ueus.GrayData)
	builder.WriteString(", ")
	builder.WriteString("is_flow_limit=")
	builder.WriteString(fmt.Sprintf("%v", ueus.IsFlowLimit))
	builder.WriteString(", ")
	builder.WriteString("flow_limit_data=")
	builder.WriteString(ueus.FlowLimitData)
	builder.WriteString(", ")
	builder.WriteString("is_del=")
	builder.WriteString(fmt.Sprintf("%v", ueus.IsDel))
	builder.WriteString(", ")
	builder.WriteString("create_at=")
	builder.WriteString(ueus.CreateAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_at=")
	builder.WriteString(ueus.UpdateAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UpgradeElectronUpgradeStrategies is a parsable slice of UpgradeElectronUpgradeStrategy.
type UpgradeElectronUpgradeStrategies []*UpgradeElectronUpgradeStrategy
