// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"upgradelink-admin-upgrade/server/ent/upgradeconfiguration"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeConfigurationCreate is the builder for creating a UpgradeConfiguration entity.
type UpgradeConfigurationCreate struct {
	config
	mutation *UpgradeConfigurationMutation
	hooks    []Hook
}

// SetCompanyID sets the "company_id" field.
func (ucc *UpgradeConfigurationCreate) SetCompanyID(i int) *UpgradeConfigurationCreate {
	ucc.mutation.SetCompanyID(i)
	return ucc
}

// SetKey sets the "key" field.
func (ucc *UpgradeConfigurationCreate) SetKey(s string) *UpgradeConfigurationCreate {
	ucc.mutation.SetKey(s)
	return ucc
}

// SetName sets the "name" field.
func (ucc *UpgradeConfigurationCreate) SetName(s string) *UpgradeConfigurationCreate {
	ucc.mutation.SetName(s)
	return ucc
}

// SetDescription sets the "description" field.
func (ucc *UpgradeConfigurationCreate) SetDescription(s string) *UpgradeConfigurationCreate {
	ucc.mutation.SetDescription(s)
	return ucc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ucc *UpgradeConfigurationCreate) SetNillableDescription(s *string) *UpgradeConfigurationCreate {
	if s != nil {
		ucc.SetDescription(*s)
	}
	return ucc
}

// SetIsDel sets the "is_del" field.
func (ucc *UpgradeConfigurationCreate) SetIsDel(i int32) *UpgradeConfigurationCreate {
	ucc.mutation.SetIsDel(i)
	return ucc
}

// SetCreateAt sets the "create_at" field.
func (ucc *UpgradeConfigurationCreate) SetCreateAt(t time.Time) *UpgradeConfigurationCreate {
	ucc.mutation.SetCreateAt(t)
	return ucc
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (ucc *UpgradeConfigurationCreate) SetNillableCreateAt(t *time.Time) *UpgradeConfigurationCreate {
	if t != nil {
		ucc.SetCreateAt(*t)
	}
	return ucc
}

// SetUpdateAt sets the "update_at" field.
func (ucc *UpgradeConfigurationCreate) SetUpdateAt(t time.Time) *UpgradeConfigurationCreate {
	ucc.mutation.SetUpdateAt(t)
	return ucc
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (ucc *UpgradeConfigurationCreate) SetNillableUpdateAt(t *time.Time) *UpgradeConfigurationCreate {
	if t != nil {
		ucc.SetUpdateAt(*t)
	}
	return ucc
}

// SetID sets the "id" field.
func (ucc *UpgradeConfigurationCreate) SetID(i int) *UpgradeConfigurationCreate {
	ucc.mutation.SetID(i)
	return ucc
}

// Mutation returns the UpgradeConfigurationMutation object of the builder.
func (ucc *UpgradeConfigurationCreate) Mutation() *UpgradeConfigurationMutation {
	return ucc.mutation
}

// Save creates the UpgradeConfiguration in the database.
func (ucc *UpgradeConfigurationCreate) Save(ctx context.Context) (*UpgradeConfiguration, error) {
	return withHooks(ctx, ucc.sqlSave, ucc.mutation, ucc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ucc *UpgradeConfigurationCreate) SaveX(ctx context.Context) *UpgradeConfiguration {
	v, err := ucc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ucc *UpgradeConfigurationCreate) Exec(ctx context.Context) error {
	_, err := ucc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ucc *UpgradeConfigurationCreate) ExecX(ctx context.Context) {
	if err := ucc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ucc *UpgradeConfigurationCreate) check() error {
	if _, ok := ucc.mutation.CompanyID(); !ok {
		return &ValidationError{Name: "company_id", err: errors.New(`ent: missing required field "UpgradeConfiguration.company_id"`)}
	}
	if _, ok := ucc.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "UpgradeConfiguration.key"`)}
	}
	if _, ok := ucc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "UpgradeConfiguration.name"`)}
	}
	if _, ok := ucc.mutation.IsDel(); !ok {
		return &ValidationError{Name: "is_del", err: errors.New(`ent: missing required field "UpgradeConfiguration.is_del"`)}
	}
	return nil
}

func (ucc *UpgradeConfigurationCreate) sqlSave(ctx context.Context) (*UpgradeConfiguration, error) {
	if err := ucc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ucc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ucc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	ucc.mutation.id = &_node.ID
	ucc.mutation.done = true
	return _node, nil
}

func (ucc *UpgradeConfigurationCreate) createSpec() (*UpgradeConfiguration, *sqlgraph.CreateSpec) {
	var (
		_node = &UpgradeConfiguration{config: ucc.config}
		_spec = sqlgraph.NewCreateSpec(upgradeconfiguration.Table, sqlgraph.NewFieldSpec(upgradeconfiguration.FieldID, field.TypeInt))
	)
	if id, ok := ucc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ucc.mutation.CompanyID(); ok {
		_spec.SetField(upgradeconfiguration.FieldCompanyID, field.TypeInt, value)
		_node.CompanyID = value
	}
	if value, ok := ucc.mutation.Key(); ok {
		_spec.SetField(upgradeconfiguration.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := ucc.mutation.Name(); ok {
		_spec.SetField(upgradeconfiguration.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := ucc.mutation.Description(); ok {
		_spec.SetField(upgradeconfiguration.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := ucc.mutation.IsDel(); ok {
		_spec.SetField(upgradeconfiguration.FieldIsDel, field.TypeInt32, value)
		_node.IsDel = value
	}
	if value, ok := ucc.mutation.CreateAt(); ok {
		_spec.SetField(upgradeconfiguration.FieldCreateAt, field.TypeTime, value)
		_node.CreateAt = value
	}
	if value, ok := ucc.mutation.UpdateAt(); ok {
		_spec.SetField(upgradeconfiguration.FieldUpdateAt, field.TypeTime, value)
		_node.UpdateAt = value
	}
	return _node, _spec
}

// UpgradeConfigurationCreateBulk is the builder for creating many UpgradeConfiguration entities in bulk.
type UpgradeConfigurationCreateBulk struct {
	config
	err      error
	builders []*UpgradeConfigurationCreate
}

// Save creates the UpgradeConfiguration entities in the database.
func (uccb *UpgradeConfigurationCreateBulk) Save(ctx context.Context) ([]*UpgradeConfiguration, error) {
	if uccb.err != nil {
		return nil, uccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(uccb.builders))
	nodes := make([]*UpgradeConfiguration, len(uccb.builders))
	mutators := make([]Mutator, len(uccb.builders))
	for i := range uccb.builders {
		func(i int, root context.Context) {
			builder := uccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpgradeConfigurationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uccb *UpgradeConfigurationCreateBulk) SaveX(ctx context.Context) []*UpgradeConfiguration {
	v, err := uccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uccb *UpgradeConfigurationCreateBulk) Exec(ctx context.Context) error {
	_, err := uccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uccb *UpgradeConfigurationCreateBulk) ExecX(ctx context.Context) {
	if err := uccb.Exec(ctx); err != nil {
		panic(err)
	}
}
