// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"upgradelink-admin-upgrade/server/ent/upgradedevgrouprelation"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeDevGroupRelationCreate is the builder for creating a UpgradeDevGroupRelation entity.
type UpgradeDevGroupRelationCreate struct {
	config
	mutation *UpgradeDevGroupRelationMutation
	hooks    []Hook
}

// SetDevID sets the "dev_id" field.
func (udgrc *UpgradeDevGroupRelationCreate) SetDevID(i int) *UpgradeDevGroupRelationCreate {
	udgrc.mutation.SetDevID(i)
	return udgrc
}

// SetDevGroupID sets the "dev_group_id" field.
func (udgrc *UpgradeDevGroupRelationCreate) SetDevGroupID(i int) *UpgradeDevGroupRelationCreate {
	udgrc.mutation.SetDevGroupID(i)
	return udgrc
}

// SetIsDel sets the "is_del" field.
func (udgrc *UpgradeDevGroupRelationCreate) SetIsDel(i int32) *UpgradeDevGroupRelationCreate {
	udgrc.mutation.SetIsDel(i)
	return udgrc
}

// SetCreateAt sets the "create_at" field.
func (udgrc *UpgradeDevGroupRelationCreate) SetCreateAt(t time.Time) *UpgradeDevGroupRelationCreate {
	udgrc.mutation.SetCreateAt(t)
	return udgrc
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (udgrc *UpgradeDevGroupRelationCreate) SetNillableCreateAt(t *time.Time) *UpgradeDevGroupRelationCreate {
	if t != nil {
		udgrc.SetCreateAt(*t)
	}
	return udgrc
}

// SetUpdateAt sets the "update_at" field.
func (udgrc *UpgradeDevGroupRelationCreate) SetUpdateAt(t time.Time) *UpgradeDevGroupRelationCreate {
	udgrc.mutation.SetUpdateAt(t)
	return udgrc
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (udgrc *UpgradeDevGroupRelationCreate) SetNillableUpdateAt(t *time.Time) *UpgradeDevGroupRelationCreate {
	if t != nil {
		udgrc.SetUpdateAt(*t)
	}
	return udgrc
}

// SetID sets the "id" field.
func (udgrc *UpgradeDevGroupRelationCreate) SetID(i int) *UpgradeDevGroupRelationCreate {
	udgrc.mutation.SetID(i)
	return udgrc
}

// Mutation returns the UpgradeDevGroupRelationMutation object of the builder.
func (udgrc *UpgradeDevGroupRelationCreate) Mutation() *UpgradeDevGroupRelationMutation {
	return udgrc.mutation
}

// Save creates the UpgradeDevGroupRelation in the database.
func (udgrc *UpgradeDevGroupRelationCreate) Save(ctx context.Context) (*UpgradeDevGroupRelation, error) {
	return withHooks(ctx, udgrc.sqlSave, udgrc.mutation, udgrc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (udgrc *UpgradeDevGroupRelationCreate) SaveX(ctx context.Context) *UpgradeDevGroupRelation {
	v, err := udgrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (udgrc *UpgradeDevGroupRelationCreate) Exec(ctx context.Context) error {
	_, err := udgrc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (udgrc *UpgradeDevGroupRelationCreate) ExecX(ctx context.Context) {
	if err := udgrc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (udgrc *UpgradeDevGroupRelationCreate) check() error {
	if _, ok := udgrc.mutation.DevID(); !ok {
		return &ValidationError{Name: "dev_id", err: errors.New(`ent: missing required field "UpgradeDevGroupRelation.dev_id"`)}
	}
	if _, ok := udgrc.mutation.DevGroupID(); !ok {
		return &ValidationError{Name: "dev_group_id", err: errors.New(`ent: missing required field "UpgradeDevGroupRelation.dev_group_id"`)}
	}
	if _, ok := udgrc.mutation.IsDel(); !ok {
		return &ValidationError{Name: "is_del", err: errors.New(`ent: missing required field "UpgradeDevGroupRelation.is_del"`)}
	}
	return nil
}

func (udgrc *UpgradeDevGroupRelationCreate) sqlSave(ctx context.Context) (*UpgradeDevGroupRelation, error) {
	if err := udgrc.check(); err != nil {
		return nil, err
	}
	_node, _spec := udgrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, udgrc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	udgrc.mutation.id = &_node.ID
	udgrc.mutation.done = true
	return _node, nil
}

func (udgrc *UpgradeDevGroupRelationCreate) createSpec() (*UpgradeDevGroupRelation, *sqlgraph.CreateSpec) {
	var (
		_node = &UpgradeDevGroupRelation{config: udgrc.config}
		_spec = sqlgraph.NewCreateSpec(upgradedevgrouprelation.Table, sqlgraph.NewFieldSpec(upgradedevgrouprelation.FieldID, field.TypeInt))
	)
	if id, ok := udgrc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := udgrc.mutation.DevID(); ok {
		_spec.SetField(upgradedevgrouprelation.FieldDevID, field.TypeInt, value)
		_node.DevID = value
	}
	if value, ok := udgrc.mutation.DevGroupID(); ok {
		_spec.SetField(upgradedevgrouprelation.FieldDevGroupID, field.TypeInt, value)
		_node.DevGroupID = value
	}
	if value, ok := udgrc.mutation.IsDel(); ok {
		_spec.SetField(upgradedevgrouprelation.FieldIsDel, field.TypeInt32, value)
		_node.IsDel = value
	}
	if value, ok := udgrc.mutation.CreateAt(); ok {
		_spec.SetField(upgradedevgrouprelation.FieldCreateAt, field.TypeTime, value)
		_node.CreateAt = value
	}
	if value, ok := udgrc.mutation.UpdateAt(); ok {
		_spec.SetField(upgradedevgrouprelation.FieldUpdateAt, field.TypeTime, value)
		_node.UpdateAt = value
	}
	return _node, _spec
}

// UpgradeDevGroupRelationCreateBulk is the builder for creating many UpgradeDevGroupRelation entities in bulk.
type UpgradeDevGroupRelationCreateBulk struct {
	config
	err      error
	builders []*UpgradeDevGroupRelationCreate
}

// Save creates the UpgradeDevGroupRelation entities in the database.
func (udgrcb *UpgradeDevGroupRelationCreateBulk) Save(ctx context.Context) ([]*UpgradeDevGroupRelation, error) {
	if udgrcb.err != nil {
		return nil, udgrcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(udgrcb.builders))
	nodes := make([]*UpgradeDevGroupRelation, len(udgrcb.builders))
	mutators := make([]Mutator, len(udgrcb.builders))
	for i := range udgrcb.builders {
		func(i int, root context.Context) {
			builder := udgrcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpgradeDevGroupRelationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, udgrcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, udgrcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, udgrcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (udgrcb *UpgradeDevGroupRelationCreateBulk) SaveX(ctx context.Context) []*UpgradeDevGroupRelation {
	v, err := udgrcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (udgrcb *UpgradeDevGroupRelationCreateBulk) Exec(ctx context.Context) error {
	_, err := udgrcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (udgrcb *UpgradeDevGroupRelationCreateBulk) ExecX(ctx context.Context) {
	if err := udgrcb.Exec(ctx); err != nil {
		panic(err)
	}
}
