// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"upgradelink-admin-upgrade/server/ent/upgradeconfigurationupgradestrategyflowlimitstrategy"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate is the builder for creating a UpgradeConfigurationUpgradeStrategyFlowLimitStrategy entity.
type UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate struct {
	config
	mutation *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyMutation
	hooks    []Hook
}

// SetEnable sets the "enable" field.
func (ucusflsc *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate) SetEnable(i int32) *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate {
	ucusflsc.mutation.SetEnable(i)
	return ucusflsc
}

// SetBeginTime sets the "begin_time" field.
func (ucusflsc *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate) SetBeginTime(s string) *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate {
	ucusflsc.mutation.SetBeginTime(s)
	return ucusflsc
}

// SetEndTime sets the "end_time" field.
func (ucusflsc *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate) SetEndTime(s string) *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate {
	ucusflsc.mutation.SetEndTime(s)
	return ucusflsc
}

// SetDimension sets the "dimension" field.
func (ucusflsc *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate) SetDimension(i int32) *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate {
	ucusflsc.mutation.SetDimension(i)
	return ucusflsc
}

// SetLimit sets the "limit" field.
func (ucusflsc *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate) SetLimit(i int) *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate {
	ucusflsc.mutation.SetLimit(i)
	return ucusflsc
}

// SetIsDel sets the "is_del" field.
func (ucusflsc *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate) SetIsDel(i int32) *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate {
	ucusflsc.mutation.SetIsDel(i)
	return ucusflsc
}

// SetCreateAt sets the "create_at" field.
func (ucusflsc *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate) SetCreateAt(t time.Time) *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate {
	ucusflsc.mutation.SetCreateAt(t)
	return ucusflsc
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (ucusflsc *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate) SetNillableCreateAt(t *time.Time) *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate {
	if t != nil {
		ucusflsc.SetCreateAt(*t)
	}
	return ucusflsc
}

// SetUpdateAt sets the "update_at" field.
func (ucusflsc *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate) SetUpdateAt(t time.Time) *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate {
	ucusflsc.mutation.SetUpdateAt(t)
	return ucusflsc
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (ucusflsc *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate) SetNillableUpdateAt(t *time.Time) *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate {
	if t != nil {
		ucusflsc.SetUpdateAt(*t)
	}
	return ucusflsc
}

// SetID sets the "id" field.
func (ucusflsc *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate) SetID(i int) *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate {
	ucusflsc.mutation.SetID(i)
	return ucusflsc
}

// Mutation returns the UpgradeConfigurationUpgradeStrategyFlowLimitStrategyMutation object of the builder.
func (ucusflsc *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate) Mutation() *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyMutation {
	return ucusflsc.mutation
}

// Save creates the UpgradeConfigurationUpgradeStrategyFlowLimitStrategy in the database.
func (ucusflsc *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate) Save(ctx context.Context) (*UpgradeConfigurationUpgradeStrategyFlowLimitStrategy, error) {
	return withHooks(ctx, ucusflsc.sqlSave, ucusflsc.mutation, ucusflsc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ucusflsc *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate) SaveX(ctx context.Context) *UpgradeConfigurationUpgradeStrategyFlowLimitStrategy {
	v, err := ucusflsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ucusflsc *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate) Exec(ctx context.Context) error {
	_, err := ucusflsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ucusflsc *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate) ExecX(ctx context.Context) {
	if err := ucusflsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ucusflsc *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate) check() error {
	if _, ok := ucusflsc.mutation.Enable(); !ok {
		return &ValidationError{Name: "enable", err: errors.New(`ent: missing required field "UpgradeConfigurationUpgradeStrategyFlowLimitStrategy.enable"`)}
	}
	if _, ok := ucusflsc.mutation.BeginTime(); !ok {
		return &ValidationError{Name: "begin_time", err: errors.New(`ent: missing required field "UpgradeConfigurationUpgradeStrategyFlowLimitStrategy.begin_time"`)}
	}
	if _, ok := ucusflsc.mutation.EndTime(); !ok {
		return &ValidationError{Name: "end_time", err: errors.New(`ent: missing required field "UpgradeConfigurationUpgradeStrategyFlowLimitStrategy.end_time"`)}
	}
	if _, ok := ucusflsc.mutation.Dimension(); !ok {
		return &ValidationError{Name: "dimension", err: errors.New(`ent: missing required field "UpgradeConfigurationUpgradeStrategyFlowLimitStrategy.dimension"`)}
	}
	if _, ok := ucusflsc.mutation.Limit(); !ok {
		return &ValidationError{Name: "limit", err: errors.New(`ent: missing required field "UpgradeConfigurationUpgradeStrategyFlowLimitStrategy.limit"`)}
	}
	if _, ok := ucusflsc.mutation.IsDel(); !ok {
		return &ValidationError{Name: "is_del", err: errors.New(`ent: missing required field "UpgradeConfigurationUpgradeStrategyFlowLimitStrategy.is_del"`)}
	}
	return nil
}

func (ucusflsc *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate) sqlSave(ctx context.Context) (*UpgradeConfigurationUpgradeStrategyFlowLimitStrategy, error) {
	if err := ucusflsc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ucusflsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ucusflsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	ucusflsc.mutation.id = &_node.ID
	ucusflsc.mutation.done = true
	return _node, nil
}

func (ucusflsc *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate) createSpec() (*UpgradeConfigurationUpgradeStrategyFlowLimitStrategy, *sqlgraph.CreateSpec) {
	var (
		_node = &UpgradeConfigurationUpgradeStrategyFlowLimitStrategy{config: ucusflsc.config}
		_spec = sqlgraph.NewCreateSpec(upgradeconfigurationupgradestrategyflowlimitstrategy.Table, sqlgraph.NewFieldSpec(upgradeconfigurationupgradestrategyflowlimitstrategy.FieldID, field.TypeInt))
	)
	if id, ok := ucusflsc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ucusflsc.mutation.Enable(); ok {
		_spec.SetField(upgradeconfigurationupgradestrategyflowlimitstrategy.FieldEnable, field.TypeInt32, value)
		_node.Enable = value
	}
	if value, ok := ucusflsc.mutation.BeginTime(); ok {
		_spec.SetField(upgradeconfigurationupgradestrategyflowlimitstrategy.FieldBeginTime, field.TypeString, value)
		_node.BeginTime = value
	}
	if value, ok := ucusflsc.mutation.EndTime(); ok {
		_spec.SetField(upgradeconfigurationupgradestrategyflowlimitstrategy.FieldEndTime, field.TypeString, value)
		_node.EndTime = value
	}
	if value, ok := ucusflsc.mutation.Dimension(); ok {
		_spec.SetField(upgradeconfigurationupgradestrategyflowlimitstrategy.FieldDimension, field.TypeInt32, value)
		_node.Dimension = value
	}
	if value, ok := ucusflsc.mutation.Limit(); ok {
		_spec.SetField(upgradeconfigurationupgradestrategyflowlimitstrategy.FieldLimit, field.TypeInt, value)
		_node.Limit = value
	}
	if value, ok := ucusflsc.mutation.IsDel(); ok {
		_spec.SetField(upgradeconfigurationupgradestrategyflowlimitstrategy.FieldIsDel, field.TypeInt32, value)
		_node.IsDel = value
	}
	if value, ok := ucusflsc.mutation.CreateAt(); ok {
		_spec.SetField(upgradeconfigurationupgradestrategyflowlimitstrategy.FieldCreateAt, field.TypeTime, value)
		_node.CreateAt = value
	}
	if value, ok := ucusflsc.mutation.UpdateAt(); ok {
		_spec.SetField(upgradeconfigurationupgradestrategyflowlimitstrategy.FieldUpdateAt, field.TypeTime, value)
		_node.UpdateAt = value
	}
	return _node, _spec
}

// UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreateBulk is the builder for creating many UpgradeConfigurationUpgradeStrategyFlowLimitStrategy entities in bulk.
type UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreateBulk struct {
	config
	err      error
	builders []*UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreate
}

// Save creates the UpgradeConfigurationUpgradeStrategyFlowLimitStrategy entities in the database.
func (ucusflscb *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreateBulk) Save(ctx context.Context) ([]*UpgradeConfigurationUpgradeStrategyFlowLimitStrategy, error) {
	if ucusflscb.err != nil {
		return nil, ucusflscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ucusflscb.builders))
	nodes := make([]*UpgradeConfigurationUpgradeStrategyFlowLimitStrategy, len(ucusflscb.builders))
	mutators := make([]Mutator, len(ucusflscb.builders))
	for i := range ucusflscb.builders {
		func(i int, root context.Context) {
			builder := ucusflscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpgradeConfigurationUpgradeStrategyFlowLimitStrategyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ucusflscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ucusflscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ucusflscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ucusflscb *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreateBulk) SaveX(ctx context.Context) []*UpgradeConfigurationUpgradeStrategyFlowLimitStrategy {
	v, err := ucusflscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ucusflscb *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreateBulk) Exec(ctx context.Context) error {
	_, err := ucusflscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ucusflscb *UpgradeConfigurationUpgradeStrategyFlowLimitStrategyCreateBulk) ExecX(ctx context.Context) {
	if err := ucusflscb.Exec(ctx); err != nil {
		panic(err)
	}
}
