// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"upgradelink-admin-upgrade/ent/predicate"
	"upgradelink-admin-upgrade/ent/upgradedev"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeDevQuery is the builder for querying UpgradeDev entities.
type UpgradeDevQuery struct {
	config
	ctx        *QueryContext
	order      []upgradedev.OrderOption
	inters     []Interceptor
	predicates []predicate.UpgradeDev
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UpgradeDevQuery builder.
func (udq *UpgradeDevQuery) Where(ps ...predicate.UpgradeDev) *UpgradeDevQuery {
	udq.predicates = append(udq.predicates, ps...)
	return udq
}

// Limit the number of records to be returned by this query.
func (udq *UpgradeDevQuery) Limit(limit int) *UpgradeDevQuery {
	udq.ctx.Limit = &limit
	return udq
}

// Offset to start from.
func (udq *UpgradeDevQuery) Offset(offset int) *UpgradeDevQuery {
	udq.ctx.Offset = &offset
	return udq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (udq *UpgradeDevQuery) Unique(unique bool) *UpgradeDevQuery {
	udq.ctx.Unique = &unique
	return udq
}

// Order specifies how the records should be ordered.
func (udq *UpgradeDevQuery) Order(o ...upgradedev.OrderOption) *UpgradeDevQuery {
	udq.order = append(udq.order, o...)
	return udq
}

// First returns the first UpgradeDev entity from the query.
// Returns a *NotFoundError when no UpgradeDev was found.
func (udq *UpgradeDevQuery) First(ctx context.Context) (*UpgradeDev, error) {
	nodes, err := udq.Limit(1).All(setContextOp(ctx, udq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{upgradedev.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (udq *UpgradeDevQuery) FirstX(ctx context.Context) *UpgradeDev {
	node, err := udq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UpgradeDev ID from the query.
// Returns a *NotFoundError when no UpgradeDev ID was found.
func (udq *UpgradeDevQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = udq.Limit(1).IDs(setContextOp(ctx, udq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{upgradedev.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (udq *UpgradeDevQuery) FirstIDX(ctx context.Context) int {
	id, err := udq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UpgradeDev entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UpgradeDev entity is found.
// Returns a *NotFoundError when no UpgradeDev entities are found.
func (udq *UpgradeDevQuery) Only(ctx context.Context) (*UpgradeDev, error) {
	nodes, err := udq.Limit(2).All(setContextOp(ctx, udq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{upgradedev.Label}
	default:
		return nil, &NotSingularError{upgradedev.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (udq *UpgradeDevQuery) OnlyX(ctx context.Context) *UpgradeDev {
	node, err := udq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UpgradeDev ID in the query.
// Returns a *NotSingularError when more than one UpgradeDev ID is found.
// Returns a *NotFoundError when no entities are found.
func (udq *UpgradeDevQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = udq.Limit(2).IDs(setContextOp(ctx, udq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{upgradedev.Label}
	default:
		err = &NotSingularError{upgradedev.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (udq *UpgradeDevQuery) OnlyIDX(ctx context.Context) int {
	id, err := udq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UpgradeDevs.
func (udq *UpgradeDevQuery) All(ctx context.Context) ([]*UpgradeDev, error) {
	ctx = setContextOp(ctx, udq.ctx, ent.OpQueryAll)
	if err := udq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UpgradeDev, *UpgradeDevQuery]()
	return withInterceptors[[]*UpgradeDev](ctx, udq, qr, udq.inters)
}

// AllX is like All, but panics if an error occurs.
func (udq *UpgradeDevQuery) AllX(ctx context.Context) []*UpgradeDev {
	nodes, err := udq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UpgradeDev IDs.
func (udq *UpgradeDevQuery) IDs(ctx context.Context) (ids []int, err error) {
	if udq.ctx.Unique == nil && udq.path != nil {
		udq.Unique(true)
	}
	ctx = setContextOp(ctx, udq.ctx, ent.OpQueryIDs)
	if err = udq.Select(upgradedev.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (udq *UpgradeDevQuery) IDsX(ctx context.Context) []int {
	ids, err := udq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (udq *UpgradeDevQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, udq.ctx, ent.OpQueryCount)
	if err := udq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, udq, querierCount[*UpgradeDevQuery](), udq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (udq *UpgradeDevQuery) CountX(ctx context.Context) int {
	count, err := udq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (udq *UpgradeDevQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, udq.ctx, ent.OpQueryExist)
	switch _, err := udq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (udq *UpgradeDevQuery) ExistX(ctx context.Context) bool {
	exist, err := udq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UpgradeDevQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (udq *UpgradeDevQuery) Clone() *UpgradeDevQuery {
	if udq == nil {
		return nil
	}
	return &UpgradeDevQuery{
		config:     udq.config,
		ctx:        udq.ctx.Clone(),
		order:      append([]upgradedev.OrderOption{}, udq.order...),
		inters:     append([]Interceptor{}, udq.inters...),
		predicates: append([]predicate.UpgradeDev{}, udq.predicates...),
		// clone intermediate query.
		sql:  udq.sql.Clone(),
		path: udq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CompanyID int `json:"company_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UpgradeDev.Query().
//		GroupBy(upgradedev.FieldCompanyID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (udq *UpgradeDevQuery) GroupBy(field string, fields ...string) *UpgradeDevGroupBy {
	udq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UpgradeDevGroupBy{build: udq}
	grbuild.flds = &udq.ctx.Fields
	grbuild.label = upgradedev.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CompanyID int `json:"company_id,omitempty"`
//	}
//
//	client.UpgradeDev.Query().
//		Select(upgradedev.FieldCompanyID).
//		Scan(ctx, &v)
func (udq *UpgradeDevQuery) Select(fields ...string) *UpgradeDevSelect {
	udq.ctx.Fields = append(udq.ctx.Fields, fields...)
	sbuild := &UpgradeDevSelect{UpgradeDevQuery: udq}
	sbuild.label = upgradedev.Label
	sbuild.flds, sbuild.scan = &udq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UpgradeDevSelect configured with the given aggregations.
func (udq *UpgradeDevQuery) Aggregate(fns ...AggregateFunc) *UpgradeDevSelect {
	return udq.Select().Aggregate(fns...)
}

func (udq *UpgradeDevQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range udq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, udq); err != nil {
				return err
			}
		}
	}
	for _, f := range udq.ctx.Fields {
		if !upgradedev.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if udq.path != nil {
		prev, err := udq.path(ctx)
		if err != nil {
			return err
		}
		udq.sql = prev
	}
	return nil
}

func (udq *UpgradeDevQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UpgradeDev, error) {
	var (
		nodes = []*UpgradeDev{}
		_spec = udq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UpgradeDev).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UpgradeDev{config: udq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, udq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (udq *UpgradeDevQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := udq.querySpec()
	_spec.Node.Columns = udq.ctx.Fields
	if len(udq.ctx.Fields) > 0 {
		_spec.Unique = udq.ctx.Unique != nil && *udq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, udq.driver, _spec)
}

func (udq *UpgradeDevQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(upgradedev.Table, upgradedev.Columns, sqlgraph.NewFieldSpec(upgradedev.FieldID, field.TypeInt))
	_spec.From = udq.sql
	if unique := udq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if udq.path != nil {
		_spec.Unique = true
	}
	if fields := udq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upgradedev.FieldID)
		for i := range fields {
			if fields[i] != upgradedev.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := udq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := udq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := udq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := udq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (udq *UpgradeDevQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(udq.driver.Dialect())
	t1 := builder.Table(upgradedev.Table)
	columns := udq.ctx.Fields
	if len(columns) == 0 {
		columns = upgradedev.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if udq.sql != nil {
		selector = udq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if udq.ctx.Unique != nil && *udq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range udq.predicates {
		p(selector)
	}
	for _, p := range udq.order {
		p(selector)
	}
	if offset := udq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := udq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UpgradeDevGroupBy is the group-by builder for UpgradeDev entities.
type UpgradeDevGroupBy struct {
	selector
	build *UpgradeDevQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (udgb *UpgradeDevGroupBy) Aggregate(fns ...AggregateFunc) *UpgradeDevGroupBy {
	udgb.fns = append(udgb.fns, fns...)
	return udgb
}

// Scan applies the selector query and scans the result into the given value.
func (udgb *UpgradeDevGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, udgb.build.ctx, ent.OpQueryGroupBy)
	if err := udgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpgradeDevQuery, *UpgradeDevGroupBy](ctx, udgb.build, udgb, udgb.build.inters, v)
}

func (udgb *UpgradeDevGroupBy) sqlScan(ctx context.Context, root *UpgradeDevQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(udgb.fns))
	for _, fn := range udgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*udgb.flds)+len(udgb.fns))
		for _, f := range *udgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*udgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := udgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UpgradeDevSelect is the builder for selecting fields of UpgradeDev entities.
type UpgradeDevSelect struct {
	*UpgradeDevQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uds *UpgradeDevSelect) Aggregate(fns ...AggregateFunc) *UpgradeDevSelect {
	uds.fns = append(uds.fns, fns...)
	return uds
}

// Scan applies the selector query and scans the result into the given value.
func (uds *UpgradeDevSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uds.ctx, ent.OpQuerySelect)
	if err := uds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpgradeDevQuery, *UpgradeDevSelect](ctx, uds.UpgradeDevQuery, uds, uds.inters, v)
}

func (uds *UpgradeDevSelect) sqlScan(ctx context.Context, root *UpgradeDevQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uds.fns))
	for _, fn := range uds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
