// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"upgradelink-admin-upgrade/ent/upgradedevgroup"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UpgradeDevGroup is the model entity for the UpgradeDevGroup schema.
type UpgradeDevGroup struct {
	config `json:"-"`
	// ID of the ent.
	// ID
	ID int `json:"id,omitempty"`
	// 公司ID
	CompanyID int `json:"company_id,omitempty"`
	// 设备分组名称
	Name string `json:"name,omitempty"`
	// 是否删除 0：正常；1：已删除
	IsDel int32 `json:"is_del,omitempty"`
	// 创建时间
	CreateAt time.Time `json:"create_at,omitempty"`
	// 修改时间
	UpdateAt     time.Time `json:"update_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpgradeDevGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upgradedevgroup.FieldID, upgradedevgroup.FieldCompanyID, upgradedevgroup.FieldIsDel:
			values[i] = new(sql.NullInt64)
		case upgradedevgroup.FieldName:
			values[i] = new(sql.NullString)
		case upgradedevgroup.FieldCreateAt, upgradedevgroup.FieldUpdateAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpgradeDevGroup fields.
func (udg *UpgradeDevGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upgradedevgroup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			udg.ID = int(value.Int64)
		case upgradedevgroup.FieldCompanyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field company_id", values[i])
			} else if value.Valid {
				udg.CompanyID = int(value.Int64)
			}
		case upgradedevgroup.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				udg.Name = value.String
			}
		case upgradedevgroup.FieldIsDel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field is_del", values[i])
			} else if value.Valid {
				udg.IsDel = int32(value.Int64)
			}
		case upgradedevgroup.FieldCreateAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_at", values[i])
			} else if value.Valid {
				udg.CreateAt = value.Time
			}
		case upgradedevgroup.FieldUpdateAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_at", values[i])
			} else if value.Valid {
				udg.UpdateAt = value.Time
			}
		default:
			udg.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpgradeDevGroup.
// This includes values selected through modifiers, order, etc.
func (udg *UpgradeDevGroup) Value(name string) (ent.Value, error) {
	return udg.selectValues.Get(name)
}

// Update returns a builder for updating this UpgradeDevGroup.
// Note that you need to call UpgradeDevGroup.Unwrap() before calling this method if this UpgradeDevGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (udg *UpgradeDevGroup) Update() *UpgradeDevGroupUpdateOne {
	return NewUpgradeDevGroupClient(udg.config).UpdateOne(udg)
}

// Unwrap unwraps the UpgradeDevGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (udg *UpgradeDevGroup) Unwrap() *UpgradeDevGroup {
	_tx, ok := udg.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpgradeDevGroup is not a transactional entity")
	}
	udg.config.driver = _tx.drv
	return udg
}

// String implements the fmt.Stringer.
func (udg *UpgradeDevGroup) String() string {
	var builder strings.Builder
	builder.WriteString("UpgradeDevGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", udg.ID))
	builder.WriteString("company_id=")
	builder.WriteString(fmt.Sprintf("%v", udg.CompanyID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(udg.Name)
	builder.WriteString(", ")
	builder.WriteString("is_del=")
	builder.WriteString(fmt.Sprintf("%v", udg.IsDel))
	builder.WriteString(", ")
	builder.WriteString("create_at=")
	builder.WriteString(udg.CreateAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_at=")
	builder.WriteString(udg.UpdateAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UpgradeDevGroups is a parsable slice of UpgradeDevGroup.
type UpgradeDevGroups []*UpgradeDevGroup
