syntax = "proto3";

// CompanySecret message

message CompanySecretInfo {
  optional uint64 id = 1;
  optional int64 created_at = 2;
  optional int64 updated_at = 3;
  // Company ID | 公司ID
  optional uint64 company_id = 4;
  // access_key | 密钥id
  optional string access_key = 5;
  // secret_key | 密钥key
  optional string secret_key = 6;
  // validity_datetime | 有效期
  optional int64  validity_datetime = 7;
  // rule_data | 规则数据
  optional string rule_data = 8;
  // 是否生效；可通过此控制策略是否生效0：失效；1：生效
  optional uint32 enable = 9;
  // 描述信息
  optional string description = 10;
  // 是否删除 0：正常；1：已删除
  optional uint32 is_del = 11;
}

message CompanySecretListResp {
  uint64 total = 1;
  repeated CompanySecretInfo data = 2;
}

message CompanySecretListReq {
  uint64 page = 1;
  uint64 page_size = 2;
  optional int64 created_at = 3;
  optional int64 updated_at = 4;
  optional uint64 company_id = 5;
  optional string access_key = 6;
  optional string secret_key = 7;
  optional int64  validity_datetime = 8;
  optional string rule_data = 9;
  optional uint32 enable = 10;
  optional string description = 11;
  optional uint32 is_del = 12;
}


service Core {

  // CompanySecret management
  // group: company_secret
  rpc createCompanySecret (CompanySecretInfo) returns (BaseIDResp);
  // group: company_secret
  rpc updateCompanySecret (CompanySecretInfo) returns (BaseResp);
  // group: company_secret
  rpc getCompanySecretList (CompanySecretListReq) returns (CompanySecretListResp);
  // group: company_secret
  rpc getCompanySecretById (IDReq) returns (CompanySecretInfo);
  // group: company_secret
  rpc deleteCompanySecret (IDsReq) returns (BaseResp);


}