// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"upgradelink-admin/server/api/internal/ent/fmscloudfile"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// FmsCloudFile is the model entity for the FmsCloudFile schema.
type FmsCloudFile struct {
	config `json:"-"`
	// ID of the ent.
	// UUID
	ID string `json:"id,omitempty"`
	// Create Time | 创建日期
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Update Time | 修改日期
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// State true: normal false: ban | 状态 true 正常 false 禁用
	State bool `json:"state,omitempty"`
	// The file's name | 文件名
	Name string `json:"name,omitempty"`
	// The file's url | 文件地址
	URL string `json:"url,omitempty"`
	// The file's size | 文件大小
	Size uint64 `json:"size,omitempty"`
	// The file's md5 | 文件的 md5
	Md5 string `json:"md5,omitempty"`
	// The file's type | 文件类型
	FileType uint8 `json:"file_type,omitempty"`
	// The user who upload the file | 上传用户的 ID
	UserID       string `json:"user_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FmsCloudFile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case fmscloudfile.FieldState:
			values[i] = new(sql.NullBool)
		case fmscloudfile.FieldSize, fmscloudfile.FieldFileType:
			values[i] = new(sql.NullInt64)
		case fmscloudfile.FieldID, fmscloudfile.FieldName, fmscloudfile.FieldURL, fmscloudfile.FieldMd5, fmscloudfile.FieldUserID:
			values[i] = new(sql.NullString)
		case fmscloudfile.FieldCreatedAt, fmscloudfile.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FmsCloudFile fields.
func (_m *FmsCloudFile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case fmscloudfile.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case fmscloudfile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case fmscloudfile.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case fmscloudfile.FieldState:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.Bool
			}
		case fmscloudfile.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case fmscloudfile.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case fmscloudfile.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = uint64(value.Int64)
			}
		case fmscloudfile.FieldMd5:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field md5", values[i])
			} else if value.Valid {
				_m.Md5 = value.String
			}
		case fmscloudfile.FieldFileType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_type", values[i])
			} else if value.Valid {
				_m.FileType = uint8(value.Int64)
			}
		case fmscloudfile.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FmsCloudFile.
// This includes values selected through modifiers, order, etc.
func (_m *FmsCloudFile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this FmsCloudFile.
// Note that you need to call FmsCloudFile.Unwrap() before calling this method if this FmsCloudFile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FmsCloudFile) Update() *FmsCloudFileUpdateOne {
	return NewFmsCloudFileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FmsCloudFile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FmsCloudFile) Unwrap() *FmsCloudFile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FmsCloudFile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FmsCloudFile) String() string {
	var builder strings.Builder
	builder.WriteString("FmsCloudFile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(fmt.Sprintf("%v", _m.Size))
	builder.WriteString(", ")
	builder.WriteString("md5=")
	builder.WriteString(_m.Md5)
	builder.WriteString(", ")
	builder.WriteString("file_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.FileType))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteByte(')')
	return builder.String()
}

// FmsCloudFiles is a parsable slice of FmsCloudFile.
type FmsCloudFiles []*FmsCloudFile
