// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"upgradelink-admin/server/api/internal/ent/predicate"
	"upgradelink-admin/server/api/internal/ent/upgradetauriupgradestrategygraystrategy"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeTauriUpgradeStrategyGrayStrategyDelete is the builder for deleting a UpgradeTauriUpgradeStrategyGrayStrategy entity.
type UpgradeTauriUpgradeStrategyGrayStrategyDelete struct {
	config
	hooks    []Hook
	mutation *UpgradeTauriUpgradeStrategyGrayStrategyMutation
}

// Where appends a list predicates to the UpgradeTauriUpgradeStrategyGrayStrategyDelete builder.
func (_d *UpgradeTauriUpgradeStrategyGrayStrategyDelete) Where(ps ...predicate.UpgradeTauriUpgradeStrategyGrayStrategy) *UpgradeTauriUpgradeStrategyGrayStrategyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UpgradeTauriUpgradeStrategyGrayStrategyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UpgradeTauriUpgradeStrategyGrayStrategyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UpgradeTauriUpgradeStrategyGrayStrategyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(upgradetauriupgradestrategygraystrategy.Table, sqlgraph.NewFieldSpec(upgradetauriupgradestrategygraystrategy.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UpgradeTauriUpgradeStrategyGrayStrategyDeleteOne is the builder for deleting a single UpgradeTauriUpgradeStrategyGrayStrategy entity.
type UpgradeTauriUpgradeStrategyGrayStrategyDeleteOne struct {
	_d *UpgradeTauriUpgradeStrategyGrayStrategyDelete
}

// Where appends a list predicates to the UpgradeTauriUpgradeStrategyGrayStrategyDelete builder.
func (_d *UpgradeTauriUpgradeStrategyGrayStrategyDeleteOne) Where(ps ...predicate.UpgradeTauriUpgradeStrategyGrayStrategy) *UpgradeTauriUpgradeStrategyGrayStrategyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UpgradeTauriUpgradeStrategyGrayStrategyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{upgradetauriupgradestrategygraystrategy.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UpgradeTauriUpgradeStrategyGrayStrategyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
