// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"upgradelink-admin/server/api/internal/ent/upgradefileupgradestrategygraystrategy"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeFileUpgradeStrategyGrayStrategyCreate is the builder for creating a UpgradeFileUpgradeStrategyGrayStrategy entity.
type UpgradeFileUpgradeStrategyGrayStrategyCreate struct {
	config
	mutation *UpgradeFileUpgradeStrategyGrayStrategyMutation
	hooks    []Hook
}

// SetEnable sets the "enable" field.
func (_c *UpgradeFileUpgradeStrategyGrayStrategyCreate) SetEnable(v int32) *UpgradeFileUpgradeStrategyGrayStrategyCreate {
	_c.mutation.SetEnable(v)
	return _c
}

// SetBeginDatetime sets the "begin_datetime" field.
func (_c *UpgradeFileUpgradeStrategyGrayStrategyCreate) SetBeginDatetime(v time.Time) *UpgradeFileUpgradeStrategyGrayStrategyCreate {
	_c.mutation.SetBeginDatetime(v)
	return _c
}

// SetEndDatetime sets the "end_datetime" field.
func (_c *UpgradeFileUpgradeStrategyGrayStrategyCreate) SetEndDatetime(v time.Time) *UpgradeFileUpgradeStrategyGrayStrategyCreate {
	_c.mutation.SetEndDatetime(v)
	return _c
}

// SetLimit sets the "limit" field.
func (_c *UpgradeFileUpgradeStrategyGrayStrategyCreate) SetLimit(v int) *UpgradeFileUpgradeStrategyGrayStrategyCreate {
	_c.mutation.SetLimit(v)
	return _c
}

// SetIsDel sets the "is_del" field.
func (_c *UpgradeFileUpgradeStrategyGrayStrategyCreate) SetIsDel(v int32) *UpgradeFileUpgradeStrategyGrayStrategyCreate {
	_c.mutation.SetIsDel(v)
	return _c
}

// SetCreateAt sets the "create_at" field.
func (_c *UpgradeFileUpgradeStrategyGrayStrategyCreate) SetCreateAt(v time.Time) *UpgradeFileUpgradeStrategyGrayStrategyCreate {
	_c.mutation.SetCreateAt(v)
	return _c
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (_c *UpgradeFileUpgradeStrategyGrayStrategyCreate) SetNillableCreateAt(v *time.Time) *UpgradeFileUpgradeStrategyGrayStrategyCreate {
	if v != nil {
		_c.SetCreateAt(*v)
	}
	return _c
}

// SetUpdateAt sets the "update_at" field.
func (_c *UpgradeFileUpgradeStrategyGrayStrategyCreate) SetUpdateAt(v time.Time) *UpgradeFileUpgradeStrategyGrayStrategyCreate {
	_c.mutation.SetUpdateAt(v)
	return _c
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (_c *UpgradeFileUpgradeStrategyGrayStrategyCreate) SetNillableUpdateAt(v *time.Time) *UpgradeFileUpgradeStrategyGrayStrategyCreate {
	if v != nil {
		_c.SetUpdateAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UpgradeFileUpgradeStrategyGrayStrategyCreate) SetID(v int) *UpgradeFileUpgradeStrategyGrayStrategyCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the UpgradeFileUpgradeStrategyGrayStrategyMutation object of the builder.
func (_c *UpgradeFileUpgradeStrategyGrayStrategyCreate) Mutation() *UpgradeFileUpgradeStrategyGrayStrategyMutation {
	return _c.mutation
}

// Save creates the UpgradeFileUpgradeStrategyGrayStrategy in the database.
func (_c *UpgradeFileUpgradeStrategyGrayStrategyCreate) Save(ctx context.Context) (*UpgradeFileUpgradeStrategyGrayStrategy, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpgradeFileUpgradeStrategyGrayStrategyCreate) SaveX(ctx context.Context) *UpgradeFileUpgradeStrategyGrayStrategy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpgradeFileUpgradeStrategyGrayStrategyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpgradeFileUpgradeStrategyGrayStrategyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpgradeFileUpgradeStrategyGrayStrategyCreate) check() error {
	if _, ok := _c.mutation.Enable(); !ok {
		return &ValidationError{Name: "enable", err: errors.New(`ent: missing required field "UpgradeFileUpgradeStrategyGrayStrategy.enable"`)}
	}
	if _, ok := _c.mutation.BeginDatetime(); !ok {
		return &ValidationError{Name: "begin_datetime", err: errors.New(`ent: missing required field "UpgradeFileUpgradeStrategyGrayStrategy.begin_datetime"`)}
	}
	if _, ok := _c.mutation.EndDatetime(); !ok {
		return &ValidationError{Name: "end_datetime", err: errors.New(`ent: missing required field "UpgradeFileUpgradeStrategyGrayStrategy.end_datetime"`)}
	}
	if _, ok := _c.mutation.Limit(); !ok {
		return &ValidationError{Name: "limit", err: errors.New(`ent: missing required field "UpgradeFileUpgradeStrategyGrayStrategy.limit"`)}
	}
	if _, ok := _c.mutation.IsDel(); !ok {
		return &ValidationError{Name: "is_del", err: errors.New(`ent: missing required field "UpgradeFileUpgradeStrategyGrayStrategy.is_del"`)}
	}
	return nil
}

func (_c *UpgradeFileUpgradeStrategyGrayStrategyCreate) sqlSave(ctx context.Context) (*UpgradeFileUpgradeStrategyGrayStrategy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpgradeFileUpgradeStrategyGrayStrategyCreate) createSpec() (*UpgradeFileUpgradeStrategyGrayStrategy, *sqlgraph.CreateSpec) {
	var (
		_node = &UpgradeFileUpgradeStrategyGrayStrategy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upgradefileupgradestrategygraystrategy.Table, sqlgraph.NewFieldSpec(upgradefileupgradestrategygraystrategy.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Enable(); ok {
		_spec.SetField(upgradefileupgradestrategygraystrategy.FieldEnable, field.TypeInt32, value)
		_node.Enable = value
	}
	if value, ok := _c.mutation.BeginDatetime(); ok {
		_spec.SetField(upgradefileupgradestrategygraystrategy.FieldBeginDatetime, field.TypeTime, value)
		_node.BeginDatetime = value
	}
	if value, ok := _c.mutation.EndDatetime(); ok {
		_spec.SetField(upgradefileupgradestrategygraystrategy.FieldEndDatetime, field.TypeTime, value)
		_node.EndDatetime = value
	}
	if value, ok := _c.mutation.Limit(); ok {
		_spec.SetField(upgradefileupgradestrategygraystrategy.FieldLimit, field.TypeInt, value)
		_node.Limit = value
	}
	if value, ok := _c.mutation.IsDel(); ok {
		_spec.SetField(upgradefileupgradestrategygraystrategy.FieldIsDel, field.TypeInt32, value)
		_node.IsDel = value
	}
	if value, ok := _c.mutation.CreateAt(); ok {
		_spec.SetField(upgradefileupgradestrategygraystrategy.FieldCreateAt, field.TypeTime, value)
		_node.CreateAt = value
	}
	if value, ok := _c.mutation.UpdateAt(); ok {
		_spec.SetField(upgradefileupgradestrategygraystrategy.FieldUpdateAt, field.TypeTime, value)
		_node.UpdateAt = value
	}
	return _node, _spec
}

// UpgradeFileUpgradeStrategyGrayStrategyCreateBulk is the builder for creating many UpgradeFileUpgradeStrategyGrayStrategy entities in bulk.
type UpgradeFileUpgradeStrategyGrayStrategyCreateBulk struct {
	config
	err      error
	builders []*UpgradeFileUpgradeStrategyGrayStrategyCreate
}

// Save creates the UpgradeFileUpgradeStrategyGrayStrategy entities in the database.
func (_c *UpgradeFileUpgradeStrategyGrayStrategyCreateBulk) Save(ctx context.Context) ([]*UpgradeFileUpgradeStrategyGrayStrategy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UpgradeFileUpgradeStrategyGrayStrategy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpgradeFileUpgradeStrategyGrayStrategyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpgradeFileUpgradeStrategyGrayStrategyCreateBulk) SaveX(ctx context.Context) []*UpgradeFileUpgradeStrategyGrayStrategy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpgradeFileUpgradeStrategyGrayStrategyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpgradeFileUpgradeStrategyGrayStrategyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
