// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"upgradelink-admin/server/api/internal/ent/predicate"
	"upgradelink-admin/server/api/internal/ent/upgradefileupgradestrategygraystrategy"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeFileUpgradeStrategyGrayStrategyUpdate is the builder for updating UpgradeFileUpgradeStrategyGrayStrategy entities.
type UpgradeFileUpgradeStrategyGrayStrategyUpdate struct {
	config
	hooks     []Hook
	mutation  *UpgradeFileUpgradeStrategyGrayStrategyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UpgradeFileUpgradeStrategyGrayStrategyUpdate builder.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) Where(ps ...predicate.UpgradeFileUpgradeStrategyGrayStrategy) *UpgradeFileUpgradeStrategyGrayStrategyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEnable sets the "enable" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) SetEnable(v int32) *UpgradeFileUpgradeStrategyGrayStrategyUpdate {
	_u.mutation.ResetEnable()
	_u.mutation.SetEnable(v)
	return _u
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) SetNillableEnable(v *int32) *UpgradeFileUpgradeStrategyGrayStrategyUpdate {
	if v != nil {
		_u.SetEnable(*v)
	}
	return _u
}

// AddEnable adds value to the "enable" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) AddEnable(v int32) *UpgradeFileUpgradeStrategyGrayStrategyUpdate {
	_u.mutation.AddEnable(v)
	return _u
}

// SetBeginDatetime sets the "begin_datetime" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) SetBeginDatetime(v time.Time) *UpgradeFileUpgradeStrategyGrayStrategyUpdate {
	_u.mutation.SetBeginDatetime(v)
	return _u
}

// SetNillableBeginDatetime sets the "begin_datetime" field if the given value is not nil.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) SetNillableBeginDatetime(v *time.Time) *UpgradeFileUpgradeStrategyGrayStrategyUpdate {
	if v != nil {
		_u.SetBeginDatetime(*v)
	}
	return _u
}

// SetEndDatetime sets the "end_datetime" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) SetEndDatetime(v time.Time) *UpgradeFileUpgradeStrategyGrayStrategyUpdate {
	_u.mutation.SetEndDatetime(v)
	return _u
}

// SetNillableEndDatetime sets the "end_datetime" field if the given value is not nil.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) SetNillableEndDatetime(v *time.Time) *UpgradeFileUpgradeStrategyGrayStrategyUpdate {
	if v != nil {
		_u.SetEndDatetime(*v)
	}
	return _u
}

// SetLimit sets the "limit" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) SetLimit(v int) *UpgradeFileUpgradeStrategyGrayStrategyUpdate {
	_u.mutation.ResetLimit()
	_u.mutation.SetLimit(v)
	return _u
}

// SetNillableLimit sets the "limit" field if the given value is not nil.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) SetNillableLimit(v *int) *UpgradeFileUpgradeStrategyGrayStrategyUpdate {
	if v != nil {
		_u.SetLimit(*v)
	}
	return _u
}

// AddLimit adds value to the "limit" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) AddLimit(v int) *UpgradeFileUpgradeStrategyGrayStrategyUpdate {
	_u.mutation.AddLimit(v)
	return _u
}

// SetIsDel sets the "is_del" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) SetIsDel(v int32) *UpgradeFileUpgradeStrategyGrayStrategyUpdate {
	_u.mutation.ResetIsDel()
	_u.mutation.SetIsDel(v)
	return _u
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) SetNillableIsDel(v *int32) *UpgradeFileUpgradeStrategyGrayStrategyUpdate {
	if v != nil {
		_u.SetIsDel(*v)
	}
	return _u
}

// AddIsDel adds value to the "is_del" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) AddIsDel(v int32) *UpgradeFileUpgradeStrategyGrayStrategyUpdate {
	_u.mutation.AddIsDel(v)
	return _u
}

// SetCreateAt sets the "create_at" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) SetCreateAt(v time.Time) *UpgradeFileUpgradeStrategyGrayStrategyUpdate {
	_u.mutation.SetCreateAt(v)
	return _u
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) SetNillableCreateAt(v *time.Time) *UpgradeFileUpgradeStrategyGrayStrategyUpdate {
	if v != nil {
		_u.SetCreateAt(*v)
	}
	return _u
}

// ClearCreateAt clears the value of the "create_at" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) ClearCreateAt() *UpgradeFileUpgradeStrategyGrayStrategyUpdate {
	_u.mutation.ClearCreateAt()
	return _u
}

// SetUpdateAt sets the "update_at" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) SetUpdateAt(v time.Time) *UpgradeFileUpgradeStrategyGrayStrategyUpdate {
	_u.mutation.SetUpdateAt(v)
	return _u
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) SetNillableUpdateAt(v *time.Time) *UpgradeFileUpgradeStrategyGrayStrategyUpdate {
	if v != nil {
		_u.SetUpdateAt(*v)
	}
	return _u
}

// ClearUpdateAt clears the value of the "update_at" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) ClearUpdateAt() *UpgradeFileUpgradeStrategyGrayStrategyUpdate {
	_u.mutation.ClearUpdateAt()
	return _u
}

// Mutation returns the UpgradeFileUpgradeStrategyGrayStrategyMutation object of the builder.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) Mutation() *UpgradeFileUpgradeStrategyGrayStrategyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UpgradeFileUpgradeStrategyGrayStrategyUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(upgradefileupgradestrategygraystrategy.Table, upgradefileupgradestrategygraystrategy.Columns, sqlgraph.NewFieldSpec(upgradefileupgradestrategygraystrategy.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Enable(); ok {
		_spec.SetField(upgradefileupgradestrategygraystrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedEnable(); ok {
		_spec.AddField(upgradefileupgradestrategygraystrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.BeginDatetime(); ok {
		_spec.SetField(upgradefileupgradestrategygraystrategy.FieldBeginDatetime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDatetime(); ok {
		_spec.SetField(upgradefileupgradestrategygraystrategy.FieldEndDatetime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Limit(); ok {
		_spec.SetField(upgradefileupgradestrategygraystrategy.FieldLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLimit(); ok {
		_spec.AddField(upgradefileupgradestrategygraystrategy.FieldLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsDel(); ok {
		_spec.SetField(upgradefileupgradestrategygraystrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedIsDel(); ok {
		_spec.AddField(upgradefileupgradestrategygraystrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.CreateAt(); ok {
		_spec.SetField(upgradefileupgradestrategygraystrategy.FieldCreateAt, field.TypeTime, value)
	}
	if _u.mutation.CreateAtCleared() {
		_spec.ClearField(upgradefileupgradestrategygraystrategy.FieldCreateAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateAt(); ok {
		_spec.SetField(upgradefileupgradestrategygraystrategy.FieldUpdateAt, field.TypeTime, value)
	}
	if _u.mutation.UpdateAtCleared() {
		_spec.ClearField(upgradefileupgradestrategygraystrategy.FieldUpdateAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upgradefileupgradestrategygraystrategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpgradeFileUpgradeStrategyGrayStrategyUpdateOne is the builder for updating a single UpgradeFileUpgradeStrategyGrayStrategy entity.
type UpgradeFileUpgradeStrategyGrayStrategyUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UpgradeFileUpgradeStrategyGrayStrategyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetEnable sets the "enable" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) SetEnable(v int32) *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne {
	_u.mutation.ResetEnable()
	_u.mutation.SetEnable(v)
	return _u
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) SetNillableEnable(v *int32) *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne {
	if v != nil {
		_u.SetEnable(*v)
	}
	return _u
}

// AddEnable adds value to the "enable" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) AddEnable(v int32) *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne {
	_u.mutation.AddEnable(v)
	return _u
}

// SetBeginDatetime sets the "begin_datetime" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) SetBeginDatetime(v time.Time) *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne {
	_u.mutation.SetBeginDatetime(v)
	return _u
}

// SetNillableBeginDatetime sets the "begin_datetime" field if the given value is not nil.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) SetNillableBeginDatetime(v *time.Time) *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne {
	if v != nil {
		_u.SetBeginDatetime(*v)
	}
	return _u
}

// SetEndDatetime sets the "end_datetime" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) SetEndDatetime(v time.Time) *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne {
	_u.mutation.SetEndDatetime(v)
	return _u
}

// SetNillableEndDatetime sets the "end_datetime" field if the given value is not nil.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) SetNillableEndDatetime(v *time.Time) *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne {
	if v != nil {
		_u.SetEndDatetime(*v)
	}
	return _u
}

// SetLimit sets the "limit" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) SetLimit(v int) *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne {
	_u.mutation.ResetLimit()
	_u.mutation.SetLimit(v)
	return _u
}

// SetNillableLimit sets the "limit" field if the given value is not nil.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) SetNillableLimit(v *int) *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne {
	if v != nil {
		_u.SetLimit(*v)
	}
	return _u
}

// AddLimit adds value to the "limit" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) AddLimit(v int) *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne {
	_u.mutation.AddLimit(v)
	return _u
}

// SetIsDel sets the "is_del" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) SetIsDel(v int32) *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne {
	_u.mutation.ResetIsDel()
	_u.mutation.SetIsDel(v)
	return _u
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) SetNillableIsDel(v *int32) *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne {
	if v != nil {
		_u.SetIsDel(*v)
	}
	return _u
}

// AddIsDel adds value to the "is_del" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) AddIsDel(v int32) *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne {
	_u.mutation.AddIsDel(v)
	return _u
}

// SetCreateAt sets the "create_at" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) SetCreateAt(v time.Time) *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne {
	_u.mutation.SetCreateAt(v)
	return _u
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) SetNillableCreateAt(v *time.Time) *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne {
	if v != nil {
		_u.SetCreateAt(*v)
	}
	return _u
}

// ClearCreateAt clears the value of the "create_at" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) ClearCreateAt() *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne {
	_u.mutation.ClearCreateAt()
	return _u
}

// SetUpdateAt sets the "update_at" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) SetUpdateAt(v time.Time) *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne {
	_u.mutation.SetUpdateAt(v)
	return _u
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) SetNillableUpdateAt(v *time.Time) *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne {
	if v != nil {
		_u.SetUpdateAt(*v)
	}
	return _u
}

// ClearUpdateAt clears the value of the "update_at" field.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) ClearUpdateAt() *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne {
	_u.mutation.ClearUpdateAt()
	return _u
}

// Mutation returns the UpgradeFileUpgradeStrategyGrayStrategyMutation object of the builder.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) Mutation() *UpgradeFileUpgradeStrategyGrayStrategyMutation {
	return _u.mutation
}

// Where appends a list predicates to the UpgradeFileUpgradeStrategyGrayStrategyUpdate builder.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) Where(ps ...predicate.UpgradeFileUpgradeStrategyGrayStrategy) *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) Select(field string, fields ...string) *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UpgradeFileUpgradeStrategyGrayStrategy entity.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) Save(ctx context.Context) (*UpgradeFileUpgradeStrategyGrayStrategy, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) SaveX(ctx context.Context) *UpgradeFileUpgradeStrategyGrayStrategy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UpgradeFileUpgradeStrategyGrayStrategyUpdateOne) sqlSave(ctx context.Context) (_node *UpgradeFileUpgradeStrategyGrayStrategy, err error) {
	_spec := sqlgraph.NewUpdateSpec(upgradefileupgradestrategygraystrategy.Table, upgradefileupgradestrategygraystrategy.Columns, sqlgraph.NewFieldSpec(upgradefileupgradestrategygraystrategy.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpgradeFileUpgradeStrategyGrayStrategy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upgradefileupgradestrategygraystrategy.FieldID)
		for _, f := range fields {
			if !upgradefileupgradestrategygraystrategy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upgradefileupgradestrategygraystrategy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Enable(); ok {
		_spec.SetField(upgradefileupgradestrategygraystrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedEnable(); ok {
		_spec.AddField(upgradefileupgradestrategygraystrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.BeginDatetime(); ok {
		_spec.SetField(upgradefileupgradestrategygraystrategy.FieldBeginDatetime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDatetime(); ok {
		_spec.SetField(upgradefileupgradestrategygraystrategy.FieldEndDatetime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Limit(); ok {
		_spec.SetField(upgradefileupgradestrategygraystrategy.FieldLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLimit(); ok {
		_spec.AddField(upgradefileupgradestrategygraystrategy.FieldLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsDel(); ok {
		_spec.SetField(upgradefileupgradestrategygraystrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedIsDel(); ok {
		_spec.AddField(upgradefileupgradestrategygraystrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.CreateAt(); ok {
		_spec.SetField(upgradefileupgradestrategygraystrategy.FieldCreateAt, field.TypeTime, value)
	}
	if _u.mutation.CreateAtCleared() {
		_spec.ClearField(upgradefileupgradestrategygraystrategy.FieldCreateAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateAt(); ok {
		_spec.SetField(upgradefileupgradestrategygraystrategy.FieldUpdateAt, field.TypeTime, value)
	}
	if _u.mutation.UpdateAtCleared() {
		_spec.ClearField(upgradefileupgradestrategygraystrategy.FieldUpdateAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &UpgradeFileUpgradeStrategyGrayStrategy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upgradefileupgradestrategygraystrategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
