// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"upgradelink-admin/server/api/internal/ent/predicate"
	"upgradelink-admin/server/api/internal/ent/upgradefileupgradestrategy"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeFileUpgradeStrategyDelete is the builder for deleting a UpgradeFileUpgradeStrategy entity.
type UpgradeFileUpgradeStrategyDelete struct {
	config
	hooks    []Hook
	mutation *UpgradeFileUpgradeStrategyMutation
}

// Where appends a list predicates to the UpgradeFileUpgradeStrategyDelete builder.
func (_d *UpgradeFileUpgradeStrategyDelete) Where(ps ...predicate.UpgradeFileUpgradeStrategy) *UpgradeFileUpgradeStrategyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UpgradeFileUpgradeStrategyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UpgradeFileUpgradeStrategyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UpgradeFileUpgradeStrategyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(upgradefileupgradestrategy.Table, sqlgraph.NewFieldSpec(upgradefileupgradestrategy.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UpgradeFileUpgradeStrategyDeleteOne is the builder for deleting a single UpgradeFileUpgradeStrategy entity.
type UpgradeFileUpgradeStrategyDeleteOne struct {
	_d *UpgradeFileUpgradeStrategyDelete
}

// Where appends a list predicates to the UpgradeFileUpgradeStrategyDelete builder.
func (_d *UpgradeFileUpgradeStrategyDeleteOne) Where(ps ...predicate.UpgradeFileUpgradeStrategy) *UpgradeFileUpgradeStrategyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UpgradeFileUpgradeStrategyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{upgradefileupgradestrategy.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UpgradeFileUpgradeStrategyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
