// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"upgradelink-admin/server/api/internal/ent/predicate"
	"upgradelink-admin/server/api/internal/ent/upgradeelectronupgradestrategy"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeElectronUpgradeStrategyUpdate is the builder for updating UpgradeElectronUpgradeStrategy entities.
type UpgradeElectronUpgradeStrategyUpdate struct {
	config
	hooks     []Hook
	mutation  *UpgradeElectronUpgradeStrategyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UpgradeElectronUpgradeStrategyUpdate builder.
func (_u *UpgradeElectronUpgradeStrategyUpdate) Where(ps ...predicate.UpgradeElectronUpgradeStrategy) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCompanyID sets the "company_id" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetCompanyID(v int) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.ResetCompanyID()
	_u.mutation.SetCompanyID(v)
	return _u
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetNillableCompanyID(v *int) *UpgradeElectronUpgradeStrategyUpdate {
	if v != nil {
		_u.SetCompanyID(*v)
	}
	return _u
}

// AddCompanyID adds value to the "company_id" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) AddCompanyID(v int) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.AddCompanyID(v)
	return _u
}

// SetEnable sets the "enable" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetEnable(v int32) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.ResetEnable()
	_u.mutation.SetEnable(v)
	return _u
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetNillableEnable(v *int32) *UpgradeElectronUpgradeStrategyUpdate {
	if v != nil {
		_u.SetEnable(*v)
	}
	return _u
}

// AddEnable adds value to the "enable" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) AddEnable(v int32) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.AddEnable(v)
	return _u
}

// SetName sets the "name" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetName(v string) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetNillableName(v *string) *UpgradeElectronUpgradeStrategyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetDescription(v string) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetNillableDescription(v *string) *UpgradeElectronUpgradeStrategyUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) ClearDescription() *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetElectronID sets the "electron_id" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetElectronID(v int) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.ResetElectronID()
	_u.mutation.SetElectronID(v)
	return _u
}

// SetNillableElectronID sets the "electron_id" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetNillableElectronID(v *int) *UpgradeElectronUpgradeStrategyUpdate {
	if v != nil {
		_u.SetElectronID(*v)
	}
	return _u
}

// AddElectronID adds value to the "electron_id" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) AddElectronID(v int) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.AddElectronID(v)
	return _u
}

// SetElectronVersionID sets the "electron_version_id" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetElectronVersionID(v int) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.ResetElectronVersionID()
	_u.mutation.SetElectronVersionID(v)
	return _u
}

// SetNillableElectronVersionID sets the "electron_version_id" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetNillableElectronVersionID(v *int) *UpgradeElectronUpgradeStrategyUpdate {
	if v != nil {
		_u.SetElectronVersionID(*v)
	}
	return _u
}

// AddElectronVersionID adds value to the "electron_version_id" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) AddElectronVersionID(v int) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.AddElectronVersionID(v)
	return _u
}

// SetBeginDatetime sets the "begin_datetime" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetBeginDatetime(v time.Time) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.SetBeginDatetime(v)
	return _u
}

// SetNillableBeginDatetime sets the "begin_datetime" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetNillableBeginDatetime(v *time.Time) *UpgradeElectronUpgradeStrategyUpdate {
	if v != nil {
		_u.SetBeginDatetime(*v)
	}
	return _u
}

// SetEndDatetime sets the "end_datetime" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetEndDatetime(v time.Time) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.SetEndDatetime(v)
	return _u
}

// SetNillableEndDatetime sets the "end_datetime" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetNillableEndDatetime(v *time.Time) *UpgradeElectronUpgradeStrategyUpdate {
	if v != nil {
		_u.SetEndDatetime(*v)
	}
	return _u
}

// SetUpgradeType sets the "upgrade_type" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetUpgradeType(v int32) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.ResetUpgradeType()
	_u.mutation.SetUpgradeType(v)
	return _u
}

// SetNillableUpgradeType sets the "upgrade_type" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetNillableUpgradeType(v *int32) *UpgradeElectronUpgradeStrategyUpdate {
	if v != nil {
		_u.SetUpgradeType(*v)
	}
	return _u
}

// AddUpgradeType adds value to the "upgrade_type" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) AddUpgradeType(v int32) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.AddUpgradeType(v)
	return _u
}

// SetPromptUpgradeContent sets the "prompt_upgrade_content" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetPromptUpgradeContent(v string) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.SetPromptUpgradeContent(v)
	return _u
}

// SetNillablePromptUpgradeContent sets the "prompt_upgrade_content" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetNillablePromptUpgradeContent(v *string) *UpgradeElectronUpgradeStrategyUpdate {
	if v != nil {
		_u.SetPromptUpgradeContent(*v)
	}
	return _u
}

// ClearPromptUpgradeContent clears the value of the "prompt_upgrade_content" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) ClearPromptUpgradeContent() *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.ClearPromptUpgradeContent()
	return _u
}

// SetUpgradeDevType sets the "upgrade_dev_type" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetUpgradeDevType(v int32) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.ResetUpgradeDevType()
	_u.mutation.SetUpgradeDevType(v)
	return _u
}

// SetNillableUpgradeDevType sets the "upgrade_dev_type" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetNillableUpgradeDevType(v *int32) *UpgradeElectronUpgradeStrategyUpdate {
	if v != nil {
		_u.SetUpgradeDevType(*v)
	}
	return _u
}

// AddUpgradeDevType adds value to the "upgrade_dev_type" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) AddUpgradeDevType(v int32) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.AddUpgradeDevType(v)
	return _u
}

// SetUpgradeDevData sets the "upgrade_dev_data" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetUpgradeDevData(v string) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.SetUpgradeDevData(v)
	return _u
}

// SetNillableUpgradeDevData sets the "upgrade_dev_data" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetNillableUpgradeDevData(v *string) *UpgradeElectronUpgradeStrategyUpdate {
	if v != nil {
		_u.SetUpgradeDevData(*v)
	}
	return _u
}

// SetUpgradeVersionType sets the "upgrade_version_type" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetUpgradeVersionType(v int32) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.ResetUpgradeVersionType()
	_u.mutation.SetUpgradeVersionType(v)
	return _u
}

// SetNillableUpgradeVersionType sets the "upgrade_version_type" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetNillableUpgradeVersionType(v *int32) *UpgradeElectronUpgradeStrategyUpdate {
	if v != nil {
		_u.SetUpgradeVersionType(*v)
	}
	return _u
}

// AddUpgradeVersionType adds value to the "upgrade_version_type" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) AddUpgradeVersionType(v int32) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.AddUpgradeVersionType(v)
	return _u
}

// SetUpgradeVersionData sets the "upgrade_version_data" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetUpgradeVersionData(v string) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.SetUpgradeVersionData(v)
	return _u
}

// SetNillableUpgradeVersionData sets the "upgrade_version_data" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetNillableUpgradeVersionData(v *string) *UpgradeElectronUpgradeStrategyUpdate {
	if v != nil {
		_u.SetUpgradeVersionData(*v)
	}
	return _u
}

// SetIsGray sets the "is_gray" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetIsGray(v int32) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.ResetIsGray()
	_u.mutation.SetIsGray(v)
	return _u
}

// SetNillableIsGray sets the "is_gray" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetNillableIsGray(v *int32) *UpgradeElectronUpgradeStrategyUpdate {
	if v != nil {
		_u.SetIsGray(*v)
	}
	return _u
}

// AddIsGray adds value to the "is_gray" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) AddIsGray(v int32) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.AddIsGray(v)
	return _u
}

// SetGrayData sets the "gray_data" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetGrayData(v string) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.SetGrayData(v)
	return _u
}

// SetNillableGrayData sets the "gray_data" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetNillableGrayData(v *string) *UpgradeElectronUpgradeStrategyUpdate {
	if v != nil {
		_u.SetGrayData(*v)
	}
	return _u
}

// SetIsFlowLimit sets the "is_flow_limit" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetIsFlowLimit(v int32) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.ResetIsFlowLimit()
	_u.mutation.SetIsFlowLimit(v)
	return _u
}

// SetNillableIsFlowLimit sets the "is_flow_limit" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetNillableIsFlowLimit(v *int32) *UpgradeElectronUpgradeStrategyUpdate {
	if v != nil {
		_u.SetIsFlowLimit(*v)
	}
	return _u
}

// AddIsFlowLimit adds value to the "is_flow_limit" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) AddIsFlowLimit(v int32) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.AddIsFlowLimit(v)
	return _u
}

// SetFlowLimitData sets the "flow_limit_data" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetFlowLimitData(v string) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.SetFlowLimitData(v)
	return _u
}

// SetNillableFlowLimitData sets the "flow_limit_data" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetNillableFlowLimitData(v *string) *UpgradeElectronUpgradeStrategyUpdate {
	if v != nil {
		_u.SetFlowLimitData(*v)
	}
	return _u
}

// SetIsDel sets the "is_del" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetIsDel(v int32) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.ResetIsDel()
	_u.mutation.SetIsDel(v)
	return _u
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetNillableIsDel(v *int32) *UpgradeElectronUpgradeStrategyUpdate {
	if v != nil {
		_u.SetIsDel(*v)
	}
	return _u
}

// AddIsDel adds value to the "is_del" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) AddIsDel(v int32) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.AddIsDel(v)
	return _u
}

// SetCreateAt sets the "create_at" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetCreateAt(v time.Time) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.SetCreateAt(v)
	return _u
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetNillableCreateAt(v *time.Time) *UpgradeElectronUpgradeStrategyUpdate {
	if v != nil {
		_u.SetCreateAt(*v)
	}
	return _u
}

// ClearCreateAt clears the value of the "create_at" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) ClearCreateAt() *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.ClearCreateAt()
	return _u
}

// SetUpdateAt sets the "update_at" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetUpdateAt(v time.Time) *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.SetUpdateAt(v)
	return _u
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SetNillableUpdateAt(v *time.Time) *UpgradeElectronUpgradeStrategyUpdate {
	if v != nil {
		_u.SetUpdateAt(*v)
	}
	return _u
}

// ClearUpdateAt clears the value of the "update_at" field.
func (_u *UpgradeElectronUpgradeStrategyUpdate) ClearUpdateAt() *UpgradeElectronUpgradeStrategyUpdate {
	_u.mutation.ClearUpdateAt()
	return _u
}

// Mutation returns the UpgradeElectronUpgradeStrategyMutation object of the builder.
func (_u *UpgradeElectronUpgradeStrategyUpdate) Mutation() *UpgradeElectronUpgradeStrategyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpgradeElectronUpgradeStrategyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpgradeElectronUpgradeStrategyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpgradeElectronUpgradeStrategyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpgradeElectronUpgradeStrategyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UpgradeElectronUpgradeStrategyUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UpgradeElectronUpgradeStrategyUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UpgradeElectronUpgradeStrategyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(upgradeelectronupgradestrategy.Table, upgradeelectronupgradestrategy.Columns, sqlgraph.NewFieldSpec(upgradeelectronupgradestrategy.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CompanyID(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCompanyID(); ok {
		_spec.AddField(upgradeelectronupgradestrategy.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enable(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedEnable(); ok {
		_spec.AddField(upgradeelectronupgradestrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(upgradeelectronupgradestrategy.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ElectronID(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldElectronID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedElectronID(); ok {
		_spec.AddField(upgradeelectronupgradestrategy.FieldElectronID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ElectronVersionID(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldElectronVersionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedElectronVersionID(); ok {
		_spec.AddField(upgradeelectronupgradestrategy.FieldElectronVersionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BeginDatetime(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldBeginDatetime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDatetime(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldEndDatetime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpgradeType(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldUpgradeType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedUpgradeType(); ok {
		_spec.AddField(upgradeelectronupgradestrategy.FieldUpgradeType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.PromptUpgradeContent(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldPromptUpgradeContent, field.TypeString, value)
	}
	if _u.mutation.PromptUpgradeContentCleared() {
		_spec.ClearField(upgradeelectronupgradestrategy.FieldPromptUpgradeContent, field.TypeString)
	}
	if value, ok := _u.mutation.UpgradeDevType(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldUpgradeDevType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedUpgradeDevType(); ok {
		_spec.AddField(upgradeelectronupgradestrategy.FieldUpgradeDevType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.UpgradeDevData(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldUpgradeDevData, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpgradeVersionType(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldUpgradeVersionType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedUpgradeVersionType(); ok {
		_spec.AddField(upgradeelectronupgradestrategy.FieldUpgradeVersionType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.UpgradeVersionData(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldUpgradeVersionData, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsGray(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldIsGray, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedIsGray(); ok {
		_spec.AddField(upgradeelectronupgradestrategy.FieldIsGray, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.GrayData(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldGrayData, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsFlowLimit(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldIsFlowLimit, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedIsFlowLimit(); ok {
		_spec.AddField(upgradeelectronupgradestrategy.FieldIsFlowLimit, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.FlowLimitData(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldFlowLimitData, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDel(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedIsDel(); ok {
		_spec.AddField(upgradeelectronupgradestrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.CreateAt(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldCreateAt, field.TypeTime, value)
	}
	if _u.mutation.CreateAtCleared() {
		_spec.ClearField(upgradeelectronupgradestrategy.FieldCreateAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateAt(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldUpdateAt, field.TypeTime, value)
	}
	if _u.mutation.UpdateAtCleared() {
		_spec.ClearField(upgradeelectronupgradestrategy.FieldUpdateAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upgradeelectronupgradestrategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpgradeElectronUpgradeStrategyUpdateOne is the builder for updating a single UpgradeElectronUpgradeStrategy entity.
type UpgradeElectronUpgradeStrategyUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UpgradeElectronUpgradeStrategyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCompanyID sets the "company_id" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetCompanyID(v int) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.ResetCompanyID()
	_u.mutation.SetCompanyID(v)
	return _u
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetNillableCompanyID(v *int) *UpgradeElectronUpgradeStrategyUpdateOne {
	if v != nil {
		_u.SetCompanyID(*v)
	}
	return _u
}

// AddCompanyID adds value to the "company_id" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) AddCompanyID(v int) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.AddCompanyID(v)
	return _u
}

// SetEnable sets the "enable" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetEnable(v int32) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.ResetEnable()
	_u.mutation.SetEnable(v)
	return _u
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetNillableEnable(v *int32) *UpgradeElectronUpgradeStrategyUpdateOne {
	if v != nil {
		_u.SetEnable(*v)
	}
	return _u
}

// AddEnable adds value to the "enable" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) AddEnable(v int32) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.AddEnable(v)
	return _u
}

// SetName sets the "name" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetName(v string) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetNillableName(v *string) *UpgradeElectronUpgradeStrategyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetDescription(v string) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetNillableDescription(v *string) *UpgradeElectronUpgradeStrategyUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) ClearDescription() *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetElectronID sets the "electron_id" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetElectronID(v int) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.ResetElectronID()
	_u.mutation.SetElectronID(v)
	return _u
}

// SetNillableElectronID sets the "electron_id" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetNillableElectronID(v *int) *UpgradeElectronUpgradeStrategyUpdateOne {
	if v != nil {
		_u.SetElectronID(*v)
	}
	return _u
}

// AddElectronID adds value to the "electron_id" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) AddElectronID(v int) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.AddElectronID(v)
	return _u
}

// SetElectronVersionID sets the "electron_version_id" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetElectronVersionID(v int) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.ResetElectronVersionID()
	_u.mutation.SetElectronVersionID(v)
	return _u
}

// SetNillableElectronVersionID sets the "electron_version_id" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetNillableElectronVersionID(v *int) *UpgradeElectronUpgradeStrategyUpdateOne {
	if v != nil {
		_u.SetElectronVersionID(*v)
	}
	return _u
}

// AddElectronVersionID adds value to the "electron_version_id" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) AddElectronVersionID(v int) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.AddElectronVersionID(v)
	return _u
}

// SetBeginDatetime sets the "begin_datetime" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetBeginDatetime(v time.Time) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.SetBeginDatetime(v)
	return _u
}

// SetNillableBeginDatetime sets the "begin_datetime" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetNillableBeginDatetime(v *time.Time) *UpgradeElectronUpgradeStrategyUpdateOne {
	if v != nil {
		_u.SetBeginDatetime(*v)
	}
	return _u
}

// SetEndDatetime sets the "end_datetime" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetEndDatetime(v time.Time) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.SetEndDatetime(v)
	return _u
}

// SetNillableEndDatetime sets the "end_datetime" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetNillableEndDatetime(v *time.Time) *UpgradeElectronUpgradeStrategyUpdateOne {
	if v != nil {
		_u.SetEndDatetime(*v)
	}
	return _u
}

// SetUpgradeType sets the "upgrade_type" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetUpgradeType(v int32) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.ResetUpgradeType()
	_u.mutation.SetUpgradeType(v)
	return _u
}

// SetNillableUpgradeType sets the "upgrade_type" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetNillableUpgradeType(v *int32) *UpgradeElectronUpgradeStrategyUpdateOne {
	if v != nil {
		_u.SetUpgradeType(*v)
	}
	return _u
}

// AddUpgradeType adds value to the "upgrade_type" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) AddUpgradeType(v int32) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.AddUpgradeType(v)
	return _u
}

// SetPromptUpgradeContent sets the "prompt_upgrade_content" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetPromptUpgradeContent(v string) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.SetPromptUpgradeContent(v)
	return _u
}

// SetNillablePromptUpgradeContent sets the "prompt_upgrade_content" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetNillablePromptUpgradeContent(v *string) *UpgradeElectronUpgradeStrategyUpdateOne {
	if v != nil {
		_u.SetPromptUpgradeContent(*v)
	}
	return _u
}

// ClearPromptUpgradeContent clears the value of the "prompt_upgrade_content" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) ClearPromptUpgradeContent() *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.ClearPromptUpgradeContent()
	return _u
}

// SetUpgradeDevType sets the "upgrade_dev_type" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetUpgradeDevType(v int32) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.ResetUpgradeDevType()
	_u.mutation.SetUpgradeDevType(v)
	return _u
}

// SetNillableUpgradeDevType sets the "upgrade_dev_type" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetNillableUpgradeDevType(v *int32) *UpgradeElectronUpgradeStrategyUpdateOne {
	if v != nil {
		_u.SetUpgradeDevType(*v)
	}
	return _u
}

// AddUpgradeDevType adds value to the "upgrade_dev_type" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) AddUpgradeDevType(v int32) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.AddUpgradeDevType(v)
	return _u
}

// SetUpgradeDevData sets the "upgrade_dev_data" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetUpgradeDevData(v string) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.SetUpgradeDevData(v)
	return _u
}

// SetNillableUpgradeDevData sets the "upgrade_dev_data" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetNillableUpgradeDevData(v *string) *UpgradeElectronUpgradeStrategyUpdateOne {
	if v != nil {
		_u.SetUpgradeDevData(*v)
	}
	return _u
}

// SetUpgradeVersionType sets the "upgrade_version_type" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetUpgradeVersionType(v int32) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.ResetUpgradeVersionType()
	_u.mutation.SetUpgradeVersionType(v)
	return _u
}

// SetNillableUpgradeVersionType sets the "upgrade_version_type" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetNillableUpgradeVersionType(v *int32) *UpgradeElectronUpgradeStrategyUpdateOne {
	if v != nil {
		_u.SetUpgradeVersionType(*v)
	}
	return _u
}

// AddUpgradeVersionType adds value to the "upgrade_version_type" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) AddUpgradeVersionType(v int32) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.AddUpgradeVersionType(v)
	return _u
}

// SetUpgradeVersionData sets the "upgrade_version_data" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetUpgradeVersionData(v string) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.SetUpgradeVersionData(v)
	return _u
}

// SetNillableUpgradeVersionData sets the "upgrade_version_data" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetNillableUpgradeVersionData(v *string) *UpgradeElectronUpgradeStrategyUpdateOne {
	if v != nil {
		_u.SetUpgradeVersionData(*v)
	}
	return _u
}

// SetIsGray sets the "is_gray" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetIsGray(v int32) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.ResetIsGray()
	_u.mutation.SetIsGray(v)
	return _u
}

// SetNillableIsGray sets the "is_gray" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetNillableIsGray(v *int32) *UpgradeElectronUpgradeStrategyUpdateOne {
	if v != nil {
		_u.SetIsGray(*v)
	}
	return _u
}

// AddIsGray adds value to the "is_gray" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) AddIsGray(v int32) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.AddIsGray(v)
	return _u
}

// SetGrayData sets the "gray_data" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetGrayData(v string) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.SetGrayData(v)
	return _u
}

// SetNillableGrayData sets the "gray_data" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetNillableGrayData(v *string) *UpgradeElectronUpgradeStrategyUpdateOne {
	if v != nil {
		_u.SetGrayData(*v)
	}
	return _u
}

// SetIsFlowLimit sets the "is_flow_limit" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetIsFlowLimit(v int32) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.ResetIsFlowLimit()
	_u.mutation.SetIsFlowLimit(v)
	return _u
}

// SetNillableIsFlowLimit sets the "is_flow_limit" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetNillableIsFlowLimit(v *int32) *UpgradeElectronUpgradeStrategyUpdateOne {
	if v != nil {
		_u.SetIsFlowLimit(*v)
	}
	return _u
}

// AddIsFlowLimit adds value to the "is_flow_limit" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) AddIsFlowLimit(v int32) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.AddIsFlowLimit(v)
	return _u
}

// SetFlowLimitData sets the "flow_limit_data" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetFlowLimitData(v string) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.SetFlowLimitData(v)
	return _u
}

// SetNillableFlowLimitData sets the "flow_limit_data" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetNillableFlowLimitData(v *string) *UpgradeElectronUpgradeStrategyUpdateOne {
	if v != nil {
		_u.SetFlowLimitData(*v)
	}
	return _u
}

// SetIsDel sets the "is_del" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetIsDel(v int32) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.ResetIsDel()
	_u.mutation.SetIsDel(v)
	return _u
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetNillableIsDel(v *int32) *UpgradeElectronUpgradeStrategyUpdateOne {
	if v != nil {
		_u.SetIsDel(*v)
	}
	return _u
}

// AddIsDel adds value to the "is_del" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) AddIsDel(v int32) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.AddIsDel(v)
	return _u
}

// SetCreateAt sets the "create_at" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetCreateAt(v time.Time) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.SetCreateAt(v)
	return _u
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetNillableCreateAt(v *time.Time) *UpgradeElectronUpgradeStrategyUpdateOne {
	if v != nil {
		_u.SetCreateAt(*v)
	}
	return _u
}

// ClearCreateAt clears the value of the "create_at" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) ClearCreateAt() *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.ClearCreateAt()
	return _u
}

// SetUpdateAt sets the "update_at" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetUpdateAt(v time.Time) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.SetUpdateAt(v)
	return _u
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SetNillableUpdateAt(v *time.Time) *UpgradeElectronUpgradeStrategyUpdateOne {
	if v != nil {
		_u.SetUpdateAt(*v)
	}
	return _u
}

// ClearUpdateAt clears the value of the "update_at" field.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) ClearUpdateAt() *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.ClearUpdateAt()
	return _u
}

// Mutation returns the UpgradeElectronUpgradeStrategyMutation object of the builder.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) Mutation() *UpgradeElectronUpgradeStrategyMutation {
	return _u.mutation
}

// Where appends a list predicates to the UpgradeElectronUpgradeStrategyUpdate builder.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) Where(ps ...predicate.UpgradeElectronUpgradeStrategy) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) Select(field string, fields ...string) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UpgradeElectronUpgradeStrategy entity.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) Save(ctx context.Context) (*UpgradeElectronUpgradeStrategy, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) SaveX(ctx context.Context) *UpgradeElectronUpgradeStrategy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UpgradeElectronUpgradeStrategyUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UpgradeElectronUpgradeStrategyUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UpgradeElectronUpgradeStrategyUpdateOne) sqlSave(ctx context.Context) (_node *UpgradeElectronUpgradeStrategy, err error) {
	_spec := sqlgraph.NewUpdateSpec(upgradeelectronupgradestrategy.Table, upgradeelectronupgradestrategy.Columns, sqlgraph.NewFieldSpec(upgradeelectronupgradestrategy.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpgradeElectronUpgradeStrategy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upgradeelectronupgradestrategy.FieldID)
		for _, f := range fields {
			if !upgradeelectronupgradestrategy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upgradeelectronupgradestrategy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CompanyID(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCompanyID(); ok {
		_spec.AddField(upgradeelectronupgradestrategy.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enable(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedEnable(); ok {
		_spec.AddField(upgradeelectronupgradestrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(upgradeelectronupgradestrategy.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ElectronID(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldElectronID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedElectronID(); ok {
		_spec.AddField(upgradeelectronupgradestrategy.FieldElectronID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ElectronVersionID(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldElectronVersionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedElectronVersionID(); ok {
		_spec.AddField(upgradeelectronupgradestrategy.FieldElectronVersionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BeginDatetime(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldBeginDatetime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDatetime(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldEndDatetime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpgradeType(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldUpgradeType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedUpgradeType(); ok {
		_spec.AddField(upgradeelectronupgradestrategy.FieldUpgradeType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.PromptUpgradeContent(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldPromptUpgradeContent, field.TypeString, value)
	}
	if _u.mutation.PromptUpgradeContentCleared() {
		_spec.ClearField(upgradeelectronupgradestrategy.FieldPromptUpgradeContent, field.TypeString)
	}
	if value, ok := _u.mutation.UpgradeDevType(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldUpgradeDevType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedUpgradeDevType(); ok {
		_spec.AddField(upgradeelectronupgradestrategy.FieldUpgradeDevType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.UpgradeDevData(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldUpgradeDevData, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpgradeVersionType(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldUpgradeVersionType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedUpgradeVersionType(); ok {
		_spec.AddField(upgradeelectronupgradestrategy.FieldUpgradeVersionType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.UpgradeVersionData(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldUpgradeVersionData, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsGray(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldIsGray, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedIsGray(); ok {
		_spec.AddField(upgradeelectronupgradestrategy.FieldIsGray, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.GrayData(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldGrayData, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsFlowLimit(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldIsFlowLimit, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedIsFlowLimit(); ok {
		_spec.AddField(upgradeelectronupgradestrategy.FieldIsFlowLimit, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.FlowLimitData(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldFlowLimitData, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDel(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedIsDel(); ok {
		_spec.AddField(upgradeelectronupgradestrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.CreateAt(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldCreateAt, field.TypeTime, value)
	}
	if _u.mutation.CreateAtCleared() {
		_spec.ClearField(upgradeelectronupgradestrategy.FieldCreateAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateAt(); ok {
		_spec.SetField(upgradeelectronupgradestrategy.FieldUpdateAt, field.TypeTime, value)
	}
	if _u.mutation.UpdateAtCleared() {
		_spec.ClearField(upgradeelectronupgradestrategy.FieldUpdateAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &UpgradeElectronUpgradeStrategy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upgradeelectronupgradestrategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
